[package]
name = "rust-formal-tools"
version = "0.1.0"
edition = "2021"
authors = ["Rust Formal Theory Team"]
description = "Rust形式化理论体系统一化与实用化工具链"
license = "MIT"

[dependencies]
# 核心依赖
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
rand = "0.8"

# 文件系统操作
walkdir = "2.3"
glob = "0.3"

# 正则表达式
regex = "1.5"

# 命令行参数
clap = { version = "4.0", features = ["derive"] }

# 日志记录
log = "0.4"
env_logger = "0.11.5"

# 错误处理
anyhow = "1.0"
thiserror = "1.0"

# 并发和同步
crossbeam = "0.8"
parking_lot = "0.12"

# 时间处理
chrono = { version = "0.4", features = ["serde"] }

# 配置管理
toml = "0.7"
config = "0.13"

# 测试框架
criterion = { version = "0.4", features = ["html_reports"] }

[dev-dependencies]
# 测试依赖
tempfile = "3.2"
mockall = "0.11"

[features]
default = ["all"]
all = ["concept-checker", "hierarchy-validator", "symbol-checker", "integration-runner"]
concept-checker = []
hierarchy-validator = []
symbol-checker = []
integration-runner = []

[[bin]]
name = "concept-checker"
path = "concept_checker.rs"
required-features = ["concept-checker"]

[[bin]]
name = "hierarchy-validator"
path = "hierarchy_validator.rs"
required-features = ["hierarchy-validator"]

[[bin]]
name = "symbol-checker"
path = "symbol_checker.rs"
required-features = ["symbol-checker"]

[[bin]]
name = "integration-runner"
path = "integration_runner.rs"
required-features = ["integration-runner"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 0
debug = true

[profile.test]
opt-level = 1
debug = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace] 