- repo: local
  hooks:
    - id: navigation-injector
      name: Navigation Block Injector
      entry: powershell -ExecutionPolicy Bypass -File scripts/navigation_injector.ps1
      language: system
      files: \.(md|rs)$
      pass_filenames: false
      always_run: true
      stages: [commit]
      description: "Automatically inject navigation blocks for new documents"
      
    - id: navigation-check
      name: Navigation Consistency Check
      entry: powershell -ExecutionPolicy Bypass -File scripts/navigation_injector.ps1 -CheckOnly
      language: system
      files: \.(md|rs)$
      pass_filenames: false
      always_run: true
      stages: [commit]
      description: "Check navigation block consistency across all documents"
