[workspace]
resolver = "3"

# 在这里添加工作空间的成员项目
members = [ "c01_own_borrow_scope", 
            "c02_type_system", 
            "c03_control_fn",
            "c04_generic", 
            "c05_threads", 
            "c06_async", 
            "c07_process", 
            "c08_algorithms", 
            "c09_design_pattern", 
            "c10_networks",  
            "c11_frameworks", 
            "c12_middlewares", 
            "c13_microservice"]


