[workspace]
resolver = "3"

members = [ "crates/c01_ownership_borrow_scope", 
            "crates/c02_type_system", 
            "crates/c03_control_fn",
            "crates/c04_generic", 
            "crates/c05_threads", 
            "crates/c06_async", 
            "crates/c07_process", 
            "crates/c08_algorithms", 
            "crates/c09_design_pattern", 
            "crates/c10_networks",  
            "crates/c11_frameworks", 
            "crates/c12_middlewares", 
            "crates/c13_microservice", 
            "crates/c14_workflow", 
            "crates/c15_blockchain", 
            "crates/c16_webassembly", 
            "crates/c17_iot", 
            "crates/c18_model"]

[profile.release]
lto = "fat"
codegen-units = 1
