[workspace]
resolver = "3"

members = [ "crates/c01_ownership_borrow_scope", 
            "crates/c02_type_system", 
            "crates/c03_control_fn",
            "crates/c04_generic", 
            "crates/c05_threads", 
            "crates/c06_async", 
            "crates/c07_process", 
            "crates/c08_algorithms", 
            "crates/c09_design_pattern", 
            "crates/c10_networks",  
            "crates/c11_frameworks", 
            "crates/c12_middlewares", 
            "crates/c13_microservice", 
            "crates/c14_workflow", 
            "crates/c15_blockchain", 
            "crates/c16_webassembly", 
            "crates/c17_iot", 
            "crates/c18_model",
            "crates/c19_ai",
            "crates/c20_distributed",
            ]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

# 工作区级别的依赖版本统一
[workspace.dependencies]
# 网络和 HTTP 相关 - 严格版本约束
reqwest = { version = "=0.12.23", features = ["json", "rustls-tls"] }
hyper = { version = "=1.7.0", features = ["full"] }
hyper-util = "=0.1.16"
hyper-rustls = "=0.27.7"
hyper-tls = "=0.6.0"
hyper-timeout = "=0.5.2"
h2 = "=0.4.12"

# Web 框架 - 严格版本约束避免冲突
axum = { version = "=0.8.4", features = ["macros", "multipart", "tracing"] }
axum-core = "=0.5.2"
tower = "=0.5.2"
tower-http = { version = "=0.6.6", features = ["cors", "trace", "timeout", "compression-gzip"] }

# 终端UI库 - 严格版本约束
crossterm = "=0.29.0"

# gRPC 相关 - 严格版本约束
tonic = { version = "=0.12.3", features = ["tls", "tls-roots", "prost"] }
tonic-build = "=0.12.3"
prost = "=0.13.5"
prost-build = "=0.13.5"
prost-derive = "=0.13.5"
prost-types = "=0.13.5"

# TLS 和加密 - 严格版本约束
rustls = { version = "=0.23.31", features = ["ring"] }
rustls-webpki = "=0.103.4"
rustls-pemfile = "=2.2.0"
tokio-rustls = "=0.26.2"
ring = "=0.17.14"
webpki-roots = "=1.0.2"

# 错误处理 - 严格版本约束
thiserror = "=2.0.16"
anyhow = "=1.0.99"

# 序列化 - 严格版本约束
serde = { version = "=1.0.219", features = ["derive"] }
serde_json = "=1.0.143"
serde_yaml = "=0.9.34"

# 异步运行时 - 严格版本约束
tokio = { version = "=1.47.1", features = ["full"] }
tokio-util = "=0.7.16"
tokio-stream = "=0.1.17"
tokio-tungstenite = "=0.21.0"
futures = "=0.3.31"
futures-util = "=0.3.31"

# 日志和追踪 - 严格版本约束
tracing = "=0.1.41"
tracing-subscriber = { version = "=0.3.20", features = ["env-filter", "json"] }
log = "=0.4.28"

# 时间处理 - 严格版本约束
chrono = { version = "=0.4.42", features = ["serde"] }
time = { version = "=0.3.43", features = ["serde", "macros"] }

# 其他常用库 - 严格版本约束
uuid = { version = "=1.18.1", features = ["v4", "serde"] }
url = "=2.5.7"
bytes = "=1.10.1"
indexmap = "=2.11.1"

# 依赖版本约束 - 在工作区依赖中统一版本