#!/usr/bin/env python3
"""
High-quality translation of Chinese doc comments with proper spacing.
Uses segment-by-segment replacement with space insertion.
"""

import os
import re

# Translation dictionary - exact phrases and words
# Organized by category for clarity
TRANSLATIONS = {
    # === Exact multi-word phrases (longest first for greedy matching) ===
    "运行所有类型系统示例": "Run all type system examples",
    "异步数据库操作示例": "Async database operation example",
    "展示如何使用异步编程进行数据库操作": "Demonstrates how to use async programming for database operations",
    "综合演示模块": "Comprehensive demonstration module",
    "本模块展示了所有线程相关功能的综合使用": "This module demonstrates comprehensive usage of all thread-related features",
    "用户数据结构": "User data structure",
    "数据库连接池": "Database connection pool",
    "获取数据库连接": "Get database connection",
    "归还数据库连接": "Return database connection",
    "执行查询": "Execute query",
    "执行插入": "Execute insert",
    "执行更新": "Execute update",
    "执行删除": "Execute delete",
    "异步用户服务": "Async user service",
    "获取所有用户": "Get all users",
    "根据ID获取用户": "Get user by ID",
    "创建新用户": "Create new user",
    "更新用户": "Update user",
    "删除用户": "Delete user",
    "批量创建用户": "Batch create users",
    "获取缓存统计": "Get cache stats",
    "数据库事务": "Database transaction",
    "主函数": "Main function",
    "性能基准测试": "Performance benchmark",
    "内存使用分析": "Memory usage analysis",
    "错误处理演示": "Error handling demonstration",
    "运行所有演示": "Run all demonstrations",
    "来源": "Source",
    
    # === Additional common short phrases ===
    "队列": "queue",
    "缓存": "cache",
    "主页": "home page",
    "随机": "random",
    "重试": "retry",
    "消息": "message",
    "矩阵": "matrix",
    "谓词": "predicate",
    "区块": "block",
    "允许": "allow",
    "递归": "recursive",
    "反例": "anti-pattern",
    "结束": "end",
    "数字": "number",
    "严重": "severe",
    "入队": "enqueue",
    "出队": "dequeue",
    "配置": "configuration",
    "交易": "transaction",
    "乘法": "multiplication",
    "约束": "constraint",
    "链表": "linked list",
    "字母": "letter",
    "超时": "timeout",
    "轮询": "poll",
    "数学": "math",
    "完成": "complete",
    "事件": "event",
    "数据": "data",
    "减法": "subtraction",
    "通知": "notify",
    "失败": "failure",
    "输入": "input",
    "结论": "conclusion",
    "圆形": "circle",
    "行号": "row number",
    "列号": "column number",
    "复数": "complex number",
    "贪心": "greedy",
    "偏置": "bias",
    "括号": "parentheses",
    "矩形": "rectangle",
    "回溯": "backtrack",
    "数组": "array",
    "加法": "addition",
    "人员": "person",
    "除法": "division",
    "大于": "greater than",
    "小于": "less than",
    "拒绝": "reject",
    "动作": "action",
    "高": "high",
    "图": "graph",
    "中": "medium",
    "低": "low",
    "删除键": "delete key",
    "熔断器": "circuit breaker",
    "错误链": "error chain",
    "查找值": "find value",
    "哈希表": "hash table",
    "断言宏": "assert macro",
    "假谓词": "false predicate",
    "连接池": "connection pool",
    "宏名称": "macro name",
    "不变式": "invariant",
    "未验证": "unverified",
    "标识符": "identifier",
    "删除值": "delete value",
    "成功率": "success rate",
    "空展开": "empty expansion",
    "数据源": "data source",
    "移除值": "remove value",
    "无动作": "no action",
    "获取值": "get value",
    "数据包": "data packet",
    "运算符": "operator",
    "证明者": "prover",
    "已验证": "verified",
    "区块链": "blockchain",
    "数据项": "data item",
    "密钥对": "key pair",
    "已停止": "stopped",
    "宏信息": "macro info",
    "位操作": "bit operation",
    "插入值": "insert value",
    "验证中": "verifying",
    "日志宏": "log macro",
    "挖矿池": "mining pool",
    "睡眠中": "sleeping",
    "证明": "proof",
    "确认号": "confirmation number",
    "涵盖": "cover",
    "用法": "usage",
    "组ID": "group ID",
    "重儿子": "heavy child",
    "让狗叫": "let dog bark",
    "语法": "syntax",
    "操作": "operation",
    "截距": "intercept",
    "预分配容量": "pre-allocate capacity",
    "逐个插入": "insert one by one",
    "不必要的克隆": "unnecessary clone",
    "手动错误映射": "manual error mapping",
    "字符串拼接": "string concatenation",
    "重复字符串分配": "repeated string allocation",
    "索引访问": "index access",
    "避免不必要的分配": "avoid unnecessary allocation",
    "使用 ? 运算符": "use ? operator",
    "解构赋值改进": "destructuring assignment improvement",
    "if let 链": "if let chains",
    "新standardlibrary API": "new standard library API",
    "Option 新method": "Option new method",
    "slice 新method": "slice new method",
    "服务器配置": "server configuration",
    "日志配置": "log configuration",
    "配置加载模式": "configuration loading pattern",
    "配置验证": "configuration validation",
    "时区处理": "timezone handling",
    "实用functionset": "utility function set",
    "常用验证模式": "common validation patterns",
    "最佳实践": "best practice",
    
    # === Common sentence starters ===
    "本 crate 提供": "This crate provides",
    "本模块提供": "This module provides",
    "本模块展示": "This module demonstrates",
    "本模块包含": "This module contains",
    "本函数展示": "This function demonstrates",
    "本函数演示": "This function demonstrates",
    "本函数实现": "This function implements",
    "本函数用于": "This function is used for",
    "本函数返回": "This function returns",
    "本函数接受": "This function accepts",
    "本函数创建": "This function creates",
    "本函数获取": "This function gets",
    "本函数设置": "This function sets",
    "本函数更新": "This function updates",
    "本函数删除": "This function deletes",
    "本函数执行": "This function executes",
    "本函数运行": "This function runs",
    "本函数调用": "This function calls",
    "本函数发送": "This function sends",
    "本函数接收": "This function receives",
    "本函数处理": "This function handles",
    "本函数计算": "This function calculates",
    "本函数生成": "This function generates",
    "本函数转换": "This function converts",
    "本函数验证": "This function validates",
    "本函数检查": "This function checks",
    "本函数测试": "This function tests",
    "本函数打印": "This function prints",
    "本函数输出": "This function outputs",
    "本函数读取": "This function reads",
    "本函数写入": "This function writes",
    "本函数复制": "This function copies",
    "本函数克隆": "This function clones",
    "本函数比较": "This function compares",
    "本函数排序": "This function sorts",
    "本函数搜索": "This function searches",
    "本函数查找": "This function finds",
    "本函数过滤": "This function filters",
    "本函数映射": "This function maps",
    "本函数归约": "This function reduces",
    "本函数折叠": "This function folds",
    "本函数聚合": "This function aggregates",
    "本函数拆分": "This function splits",
    "本函数合并": "This function merges",
    "本函数连接": "This function connects",
    "本函数断开": "This function disconnects",
    "本函数启动": "This function starts",
    "本函数停止": "This function stops",
    "本函数暂停": "This function pauses",
    "本函数恢复": "This function resumes",
    "本函数取消": "This function cancels",
    "本函数重试": "This function retries",
    "本函数等待": "This function waits",
    "本函数睡眠": "This function sleeps",
    "本函数唤醒": "This function wakes",
    "本函数通知": "This function notifies",
    "本函数广播": "This function broadcasts",
    "本函数订阅": "This function subscribes",
    "本函数发布": "This function publishes",
    "本函数注册": "This function registers",
    "本函数注销": "This function unregisters",
    "本函数登录": "This function logs in",
    "本函数登出": "This function logs out",
    "本函数认证": "This function authenticates",
    "本函数授权": "This function authorizes",
    "本函数加密": "This function encrypts",
    "本函数解密": "This function decrypts",
    "本函数压缩": "This function compresses",
    "本函数解压": "This function decompresses",
    "本函数编码": "This function encodes",
    "本函数解码": "This function decodes",
    "本函数序列化": "This function serializes",
    "本函数反序列化": "This function deserializes",
    "本函数解析": "This function parses",
    "本函数格式化": "This function formats",
    "本函数清理": "This function cleans up",
    "本函数初始化": "This function initializes",
    "本函数配置": "This function configures",
    "本函数重置": "This function resets",
    "本函数刷新": "This function flushes",
    "本函数关闭": "This function closes",
    "本函数打开": "This function opens",
    "本函数锁定": "This function locks",
    "本函数解锁": "This function unlocks",
    "本函数申请": "This function requests",
    "本函数释放": "This function releases",
    "本函数分配": "This function allocates",
    "本函数回收": "This function reclaims",
    
    # === Common nouns ===
    "演示模块": "demonstration module",
    "演示函数": "demonstration function",
    "演示结构体": "demonstration struct",
    "演示枚举": "demonstration enum",
    "演示特质": "demonstration trait",
    "演示类型": "demonstration type",
    "演示示例": "demonstration example",
    "演示代码": "demonstration code",
    "演示程序": "demonstration program",
    "演示应用": "demonstration application",
    "演示项目": "demonstration project",
    "演示系统": "demonstration system",
    "演示工具": "demonstration tool",
    "演示库": "demonstration library",
    "演示框架": "demonstration framework",
    "演示平台": "demonstration platform",
    "演示服务": "demonstration service",
    "演示微服务": "demonstration microservice",
    "演示架构": "demonstration architecture",
    "演示设计": "demonstration design",
    "演示模式": "demonstration pattern",
    "演示算法": "demonstration algorithm",
    "演示数据结构": "demonstration data structure",
    "演示数据库": "demonstration database",
    "演示网络": "demonstration network",
    "演示协议": "demonstration protocol",
    "演示接口": "demonstration interface",
    "演示API": "demonstration API",
    "演示SDK": "demonstration SDK",
    "演示CLI": "demonstration CLI",
    "演示GUI": "demonstration GUI",
    "演示TUI": "demonstration TUI",
    "演示REPL": "demonstration REPL",
    "演示DSL": "demonstration DSL",
    "演示ORM": "demonstration ORM",
    "演示RPC": "demonstration RPC",
    "演示IPC": "demonstration IPC",
    "演示MPI": "demonstration MPI",
    
    # === Single words (used for fallback) ===
    "运行": "Run",
    "所有": "all",
    "类型": "type",
    "系统": "system",
    "示例": "example",
    "综合": "comprehensive",
    "演示": "demonstration",
    "模块": "module",
    "函数": "function",
    "方法": "method",
    "结构体": "struct",
    "枚举": "enum",
    "联合": "union",
    "特质": "trait",
    "类型": "type",
    "泛型": "generic",
    "常量": "constant",
    "变量": "variable",
    "参数": "parameter",
    "返回值": "return value",
    "字段": "field",
    "属性": "attribute",
    "特性": "feature",
    "生命周期": "lifetime",
    "借用": "borrowing",
    "所有权": "ownership",
    "引用": "reference",
    "指针": "pointer",
    "原始指针": "raw pointer",
    "函数指针": "function pointer",
    "闭包捕获": "closure capture",
    "环境捕获": "environment capture",
    "移动语义": "move semantics",
    "复制语义": "copy semantics",
    "默认实现": "default implementation",
    "关联类型": "associated type",
    "关联常量": "associated constant",
    "关联函数": "associated function",
    "构造函数": "constructor",
    "析构函数": "destructor",
    "构建器": "builder",
    "工厂": "factory",
    "单例": "singleton",
    "观察者": "observer",
    "访问者": "visitor",
    "状态机": "state machine",
    "模板方法": "template method",
    "装饰器": "decorator",
    "适配器": "adapter",
    "桥接": "bridge",
    "组合": "composite",
    "外观": "facade",
    "享元": "flyweight",
    "代理模式": "proxy pattern",
    "责任链": "chain of responsibility",
    "命令": "command",
    "解释器": "interpreter",
    "迭代器模式": "iterator pattern",
    "中介者": "mediator",
    "备忘录": "memento",
    "空对象": "null object",
    "规格": "specification",
    "工作单元": "unit of work",
    "仓储": "repository",
    "领域驱动设计": "domain-driven design",
    "微服务": "microservice",
    "服务网格": "service mesh",
    "容器化": "containerization",
    "编排": "orchestration",
    "无服务器": "serverless",
    "函数即服务": "function as a service",
    "前端": "frontend",
    "后端": "backend",
    "全栈": "full-stack",
    
    # Technical terms
    "并发": "concurrency",
    "并行": "parallelism",
    "异步": "async",
    "同步": "synchronous",
    "线程": "thread",
    "进程": "process",
    "协程": "coroutine",
    "任务": "task",
    "纤程": "fiber",
    "绿色线程": "green thread",
    "原生线程": "OS thread",
    "线程池": "thread pool",
    "工作线程": "worker thread",
    "守护线程": "daemon thread",
    "主线程": "main thread",
    "子线程": "child thread",
    "父线程": "parent thread",
    "线程安全": "thread-safe",
    "线程局部": "thread-local",
    "线程亲和性": "thread affinity",
    "线程调度": "thread scheduling",
    "线程优先级": "thread priority",
    "线程同步": "thread synchronization",
    "线程通信": "thread communication",
    "线程取消": "thread cancellation",
    "线程中断": "thread interruption",
    "线程阻塞": "thread blocking",
    "线程唤醒": "thread waking",
    "线程休眠": "thread sleeping",
    "线程让步": "thread yielding",
    "线程自旋": "thread spinning",
    "线程挂起": "thread suspension",
    "线程恢复": "thread resumption",
    "线程终止": "thread termination",
    "线程加入": "thread joining",
    "线程分离": "thread detaching",
    "线程标识": "thread ID",
    "线程名称": "thread name",
    "线程状态": "thread state",
    "线程上下文": "thread context",
    "线程栈": "thread stack",
    "线程本地存储": "thread-local storage",
    
    # Memory
    "内存": "memory",
    "堆": "heap",
    "栈": "stack",
    "堆内存": "heap memory",
    "栈内存": "stack memory",
    "全局内存": "global memory",
    "静态内存": "static memory",
    "常量内存": "constant memory",
    "虚拟内存": "virtual memory",
    "物理内存": "physical memory",
    "共享内存": "shared memory",
    "内存映射": "memory mapping",
    "内存池": "memory pool",
    "内存分配器": "allocator",
    "内存布局": "memory layout",
    "内存对齐": "memory alignment",
    "内存排序": "memory ordering",
    "内存屏障": "memory barrier",
    "内存模型": "memory model",
    "内存安全": "memory safety",
    "内存泄漏": "memory leak",
    "内存溢出": "memory overflow",
    "内存不足": "out of memory",
    "段错误": "segmentation fault",
    "总线错误": "bus error",
    "双重释放": "double free",
    "使用已释放": "use-after-free",
    "缓冲区溢出": "buffer overflow",
    "栈溢出": "stack overflow",
    "堆溢出": "heap overflow",
    
    # Synchronization
    "锁": "lock",
    "互斥锁": "mutex",
    "读写锁": "rwlock",
    "自旋锁": "spinlock",
    "自适应锁": "adaptive lock",
    "递归锁": "recursive lock",
    "公平锁": "fair lock",
    "非公平锁": "unfair lock",
    "重入锁": "reentrant lock",
    "信号量": "semaphore",
    "条件变量": "condition variable",
    "屏障": "barrier",
    "无锁屏障": "lock-free barrier",
    "原子操作": "atomic operation",
    "原子变量": "atomic variable",
    "原子计数器": "atomic counter",
    "原子标志": "atomic flag",
    "原子指针": "atomic pointer",
    "比较并交换": "compare-and-swap",
    "加载链接": "load-link",
    "条件存储": "store-conditional",
    "获取-释放": "acquire-release",
    "顺序一致": "sequentially consistent",
    "松散序": "relaxed ordering",
    "发布-订阅": "publish-subscribe",
    
    # Channels
    "通道": "channel",
    "消息通道": "message channel",
    "广播通道": "broadcast channel",
    "无界通道": "unbounded channel",
    "有界通道": "bounded channel",
    "异步通道": "async channel",
    "同步通道": "sync channel",
    "多生产者单消费者": "multi-producer single-consumer",
    "单生产者单消费者": "single-producer single-consumer",
    "背压": "backpressure",
    "优先级通道": "priority channel",
    
    # Lock-free
    "无锁": "lock-free",
    "无等待": "wait-free",
    "乐观并发": "optimistic concurrency",
    "悲观并发": "pessimistic concurrency",
    "无锁队列": "lock-free queue",
    "无锁栈": "lock-free stack",
    "无锁链表": "lock-free linked list",
    "无锁哈希表": "lock-free hash map",
    "无锁跳表": "lock-free skip list",
    "无锁B+树": "lock-free B+ tree",
    "无锁环形缓冲区": "lock-free ring buffer",
    "无锁优先级队列": "lock-free priority queue",
    "无锁内存管理": "lock-free memory management",
    "危险指针": "hazard pointer",
    "引用计数": "reference counting",
    
    # Performance
    "性能": "performance",
    "优化": "optimization",
    "基准测试": "benchmark",
    "性能测试": "performance test",
    "压力测试": "stress test",
    "负载测试": "load test",
    "吞吐量测试": "throughput test",
    "延迟测试": "latency test",
    "CPU 缓存": "CPU cache",
    "缓存行": "cache line",
    "伪共享": "false sharing",
    "缓存友好": "cache-friendly",
    "缓存未命中": "cache miss",
    "缓存命中": "cache hit",
    "预取": "prefetch",
    "分支预测": "branch prediction",
    "推测执行": "speculative execution",
    "乱序执行": "out-of-order execution",
    "超标量": "superscalar",
    "流水线": "pipeline",
    "流水线停顿": "pipeline stall",
    "数据冒险": "data hazard",
    "结构冒险": "structural hazard",
    "控制冒险": "control hazard",
    "SIMD": "SIMD",
    "向量化": "vectorization",
    "自动向量化": "auto-vectorization",
    "循环展开": "loop unrolling",
    "函数内联": "function inlining",
    "尾调用优化": "tail call optimization",
    "死代码消除": "dead code elimination",
    "常量传播": "constant propagation",
    "常量折叠": "constant folding",
    "强度削弱": "strength reduction",
    "公共子表达式消除": "common subexpression elimination",
    "循环不变量外提": "loop-invariant code motion",
    "逃逸分析": "escape analysis",
    "别名分析": "alias analysis",
    "指针分析": "pointer analysis",
    "控制流分析": "control flow analysis",
    "数据流分析": "data flow analysis",
    "支配树": "dominator tree",
    "活跃变量分析": "liveness analysis",
    "可达定义分析": "reaching definition analysis",
    "可用表达式分析": "available expression analysis",
    "忙碌变量分析": "busy variable analysis",
    "部分冗余消除": "partial redundancy elimination",
    "全局值编号": "global value numbering",
    "稀疏条件常量传播": "sparse conditional constant propagation",
    "函数克隆": "function cloning",
    "轮廓引导优化": "profile-guided optimization",
    "链接时优化": "link-time optimization",
    "全程序优化": "whole-program optimization",
    "即时编译": "just-in-time compilation",
    "提前编译": "ahead-of-time compilation",
    
    # Error handling
    "错误处理": "error handling",
    "错误恢复": "error recovery",
    "错误传播": "error propagation",
    "错误转换": "error conversion",
    "错误类型": "error type",
    "错误信息": "error message",
    "错误码": "error code",
    
    # IO
    "文件操作": "file operation",
    "文件读取": "file reading",
    "文件写入": "file writing",
    "文件追加": "file appending",
    "文件创建": "file creation",
    "文件删除": "file deletion",
    "文件重命名": "file renaming",
    "文件复制": "file copying",
    "文件移动": "file moving",
    "文件元数据": "file metadata",
    "文件权限": "file permissions",
    "文件描述符": "file descriptor",
    "文件句柄": "file handle",
    "标准输入": "standard input",
    "标准输出": "standard output",
    "标准错误": "standard error",
    "管道": "pipe",
    "命名管道": "named pipe",
    "匿名管道": "anonymous pipe",
    "套接字": "socket",
    "TCP 套接字": "TCP socket",
    "UDP 套接字": "UDP socket",
    "Unix 域套接字": "Unix domain socket",
    "网络套接字": "network socket",
    "监听套接字": "listening socket",
    "连接套接字": "connected socket",
    "数据报": "datagram",
    "流": "stream",
    "字节流": "byte stream",
    "字符流": "character stream",
    "缓冲": "buffering",
    "行缓冲": "line buffering",
    "块缓冲": "block buffering",
    "无缓冲": "unbuffered",
    
    # Network
    "网络": "network",
    "网络编程": "network programming",
    "网络协议": "network protocol",
    "网络层": "network layer",
    "传输层": "transport layer",
    "应用层": "application layer",
    "物理层": "physical layer",
    "数据链路层": "data link layer",
    "会话层": "session layer",
    "表示层": "presentation layer",
    "TCP": "TCP",
    "UDP": "UDP",
    "IP": "IP",
    "IPv4": "IPv4",
    "IPv6": "IPv6",
    "HTTP": "HTTP",
    "HTTP/1.1": "HTTP/1.1",
    "HTTP/2": "HTTP/2",
    "HTTP/3": "HTTP/3",
    "QUIC": "QUIC",
    "TLS": "TLS",
    "SSL": "SSL",
    "DTLS": "DTLS",
    "WebSocket": "WebSocket",
    "gRPC": "gRPC",
    "REST": "REST",
    "JSON": "JSON",
    "XML": "XML",
    "Protobuf": "Protobuf",
    "MessagePack": "MessagePack",
    "Cap'n Proto": "Cap'n Proto",
    "FlatBuffers": "FlatBuffers",
    "Avro": "Avro",
    "Thrift": "Thrift",
    "DNS": "DNS",
    "DHCP": "DHCP",
    "NAT": "NAT",
    "VPN": "VPN",
    "代理服务器": "proxy server",
    "反向代理": "reverse proxy",
    "负载均衡器": "load balancer",
    "网关": "gateway",
    "防火墙": "firewall",
    "路由器": "router",
    "交换机": "switch",
    "集线器": "hub",
    "网桥": "bridge",
    "调制解调器": "modem",
    "网络接口卡": "NIC",
    "MAC 地址": "MAC address",
    "IP 地址": "IP address",
    "端口号": "port number",
    "子网掩码": "subnet mask",
    "默认网关": "default gateway",
    "广播地址": "broadcast address",
    "回环地址": "loopback address",
    "多播地址": "multicast address",
    "任播地址": "anycast address",
    "CIDR": "CIDR",
    "VLAN": "VLAN",
    "VXLAN": "VXLAN",
    "GRE": "GRE",
    "IPsec": "IPsec",
    "WireGuard": "WireGuard",
    "OpenVPN": "OpenVPN",
    "mTLS": "mTLS",
    "证书": "certificate",
    "根证书": "root certificate",
    "中间证书": "intermediate certificate",
    "自签名证书": "self-signed certificate",
    "证书链": "certificate chain",
    "证书吊销": "certificate revocation",
    "OCSP": "OCSP",
    "CRL": "CRL",
    "CT 日志": "CT log",
    "SCT": "SCT",
    
    # Web
    "Web": "Web",
    "Web 服务器": "Web server",
    "Web 框架": "Web framework",
    "Web 应用": "Web application",
    "Web 服务": "Web service",
    "Web API": "Web API",
    "Web 前端": "Web frontend",
    "Web 后端": "Web backend",
    "Web 全栈": "Web full-stack",
    "Web 开发": "Web development",
    "Web 设计": "Web design",
    "Web 安全": "Web security",
    "Web 性能": "Web performance",
    "Web 缓存": "Web cache",
    "Web 存储": "Web storage",
    "WebSocket": "WebSocket",
    "Server-Sent Events": "Server-Sent Events",
    "WebRTC": "WebRTC",
    "WebAssembly": "WebAssembly",
    "WASM": "WASM",
    "WASI": "WASI",
    "Service Worker": "Service Worker",
    "Progressive Web App": "Progressive Web App",
    "单页应用": "single-page application",
    "多页应用": "multi-page application",
    "服务端渲染": "server-side rendering",
    "客户端渲染": "client-side rendering",
    "同构应用": "isomorphic application",
    "静态站点生成": "static site generation",
    "Jamstack": "Jamstack",
    "无头 CMS": "headless CMS",
    "内容分发网络": "CDN",
    "边缘计算": "edge computing",
    "无服务器计算": "serverless computing",
    "函数计算": "function computing",
    "容器服务": "container service",
    "Kubernetes": "Kubernetes",
    "Docker": "Docker",
    "Podman": "Podman",
    "containerd": "containerd",
    "CRI-O": "CRI-O",
    "rkt": "rkt",
    "LXC": "LXC",
    "LXD": "LXD",
    "systemd-nspawn": "systemd-nspawn",
    "gVisor": "gVisor",
    "Kata Containers": "Kata Containers",
    "Firecracker": "Firecracker",
    "WASM 运行时": "WASM runtime",
    "WASI 运行时": "WASI runtime",
    
    # Database
    "数据库": "database",
    "关系型数据库": "relational database",
    "NoSQL 数据库": "NoSQL database",
    "文档数据库": "document database",
    "键值数据库": "key-value database",
    "列族数据库": "column-family database",
    "图数据库": "graph database",
    "时序数据库": "time-series database",
    "搜索引擎": "search engine",
    "缓存数据库": "cache database",
    "内存数据库": "in-memory database",
    "嵌入式数据库": "embedded database",
    "分布式数据库": "distributed database",
    "云数据库": "cloud database",
    "数据库连接池": "database connection pool",
    "数据库事务": "database transaction",
    "ACID": "ACID",
    "BASE": "BASE",
    "CAP 定理": "CAP theorem",
    "一致性": "consistency",
    "可用性": "availability",
    "分区容错性": "partition tolerance",
    "最终一致性": "eventual consistency",
    "强一致性": "strong consistency",
    "线性一致性": "linearizability",
    "顺序一致性": "sequential consistency",
    "因果一致性": "causal consistency",
    "会话一致性": "session consistency",
    "单调读一致性": "monotonic read consistency",
    "单调写一致性": "monotonic write consistency",
    "读己写一致性": "read-your-writes consistency",
    "读后写一致性": "writes-follow-reads consistency",
    "隔离级别": "isolation level",
    "读未提交": "read uncommitted",
    "读已提交": "read committed",
    "可重复读": "repeatable read",
    "串行化": "serializable",
    "快照隔离": "snapshot isolation",
    "乐观并发控制": "optimistic concurrency control",
    "悲观并发控制": "pessimistic concurrency control",
    "多版本并发控制": "multiversion concurrency control",
    "两阶段锁": "two-phase locking",
    "两阶段提交": "two-phase commit",
    "三阶段提交": "three-phase commit",
    "Saga 模式": "Saga pattern",
    "补偿事务": "compensating transaction",
    "事件溯源": "event sourcing",
    "CQRS": "CQRS",
    "读写分离": "read-write splitting",
    "分库分表": "sharding",
    "主从复制": "master-slave replication",
    "多主复制": "multi-master replication",
    "异步复制": "asynchronous replication",
    "同步复制": "synchronous replication",
    "半同步复制": "semi-synchronous replication",
    "逻辑复制": "logical replication",
    "物理复制": "physical replication",
    "流复制": "streaming replication",
    "热备": "hot standby",
    "温备": "warm standby",
    "冷备": "cold standby",
    "故障转移": "failover",
    "故障恢复": "failback",
    "脑裂": "split-brain",
    "选举": "election",
    "共识算法": "consensus algorithm",
    "Raft": "Raft",
    "Paxos": "Paxos",
    "ZAB": "ZAB",
    "Gossip": "Gossip",
    "SWIM": "SWIM",
    "Phi 累积失败检测": "Phi accrual failure detection",
    "心跳检测": "heartbeat detection",
    "健康检查": "health check",
    "服务发现": "service discovery",
    "服务注册": "service registration",
    "服务治理": "service governance",
    "服务网格": "service mesh",
    "Istio": "Istio",
    "Linkerd": "Linkerd",
    "Envoy": "Envoy",
    "NGINX": "NGINX",
    "HAProxy": "HAProxy",
    "Traefik": "Traefik",
    "Caddy": "Caddy",
    "Varnish": "Varnish",
    "Squid": "Squid",
    "Redis": "Redis",
    "Memcached": "Memcached",
    "Etcd": "Etcd",
    "ZooKeeper": "ZooKeeper",
    "Consul": "Consul",
    "Eureka": "Eureka",
    "Nacos": "Nacos",
    "Apollo": "Apollo",
    "Sentinel": "Sentinel",
    "Seata": "Seata",
    "ShardingSphere": "ShardingSphere",
    "MyCat": "MyCat",
    "Vitess": "Vitess",
    "Citus": "Citus",
    "TiDB": "TiDB",
    "CockroachDB": "CockroachDB",
    "YugabyteDB": "YugabyteDB",
    "Spanner": "Spanner",
    "Bigtable": "Bigtable",
    "DynamoDB": "DynamoDB",
    "Cassandra": "Cassandra",
    "ScyllaDB": "ScyllaDB",
    "MongoDB": "MongoDB",
    "PostgreSQL": "PostgreSQL",
    "MySQL": "MySQL",
    "MariaDB": "MariaDB",
    "SQLite": "SQLite",
    "SQL Server": "SQL Server",
    "Oracle": "Oracle",
    "DB2": "DB2",
    "Sybase": "Sybase",
    "Informix": "Informix",
    "Teradata": "Teradata",
    "Greenplum": "Greenplum",
    "Vertica": "Vertica",
    "ClickHouse": "ClickHouse",
    "Druid": "Druid",
    "Pinot": "Pinot",
    "InfluxDB": "InfluxDB",
    "TimescaleDB": "TimescaleDB",
    "QuestDB": "QuestDB",
    "TDengine": "TDengine",
    "IoTDB": "IoTDB",
    "Neo4j": "Neo4j",
    "JanusGraph": "JanusGraph",
    "Dgraph": "Dgraph",
    "ArangoDB": "ArangoDB",
    "OrientDB": "OrientDB",
    "TigerGraph": "TigerGraph",
    "Amazon Neptune": "Amazon Neptune",
    "Azure Cosmos DB": "Azure Cosmos DB",
    "Firebase": "Firebase",
    "Firestore": "Firestore",
    "Realm": "Realm",
    "Couchbase": "Couchbase",
    "CouchDB": "CouchDB",
    "PouchDB": "PouchDB",
    "RethinkDB": "RethinkDB",
    "FaunaDB": "FaunaDB",
    "Supabase": "Supabase",
    "PlanetScale": "PlanetScale",
    "Neon": "Neon",
    "CockroachDB Serverless": "CockroachDB Serverless",
    "YugabyteDB Managed": "YugabyteDB Managed",
    "TiDB Cloud": "TiDB Cloud",
    
    # Algorithm
    "算法": "algorithm",
    "数据结构": "data structure",
    "时间复杂度": "time complexity",
    "空间复杂度": "space complexity",
    "大 O 表示法": "Big-O notation",
    "渐近分析": "asymptotic analysis",
    "最优解": "optimal solution",
    "近似解": "approximate solution",
    "启发式": "heuristic",
    "元启发式": "metaheuristic",
    "精确算法": "exact algorithm",
    "近似算法": "approximation algorithm",
    "随机算法": "randomized algorithm",
    "确定性算法": "deterministic algorithm",
    "在线算法": "online algorithm",
    "离线算法": "offline algorithm",
    "并行算法": "parallel algorithm",
    "分布式算法": "distributed algorithm",
    "串行算法": "serial algorithm",
    "递归算法": "recursive algorithm",
    "迭代算法": "iterative algorithm",
    "分治算法": "divide and conquer algorithm",
    "贪心算法": "greedy algorithm",
    "动态规划": "dynamic programming",
    "回溯算法": "backtracking algorithm",
    "分支定界": "branch and bound",
    "剪枝": "pruning",
    "记忆化": "memoization",
    "制表": "tabulation",
    "自顶向下": "top-down",
    "自底向上": "bottom-up",
    "状态压缩": "state compression",
    "状态转移": "state transition",
    "状态空间": "state space",
    "转移方程": "transition equation",
    "初始状态": "initial state",
    "终止状态": "terminal state",
    "目标状态": "goal state",
    "边界条件": "boundary condition",
    "最优子结构": "optimal substructure",
    "重叠子问题": "overlapping subproblems",
    "无后效性": "no aftereffect",
    "排序算法": "sorting algorithm",
    "搜索算法": "searching algorithm",
    "图算法": "graph algorithm",
    "字符串算法": "string algorithm",
    "数值算法": "numerical algorithm",
    "几何算法": "geometric algorithm",
    "组合算法": "combinatorial algorithm",
    "概率算法": "probabilistic algorithm",
    "随机化算法": "randomized algorithm",
    "拉斯维加斯算法": "Las Vegas algorithm",
    "蒙特卡洛算法": "Monte Carlo algorithm",
    "舍伍德算法": "Sherwood algorithm",
    "快速排序": "quick sort",
    "归并排序": "merge sort",
    "堆排序": "heap sort",
    "插入排序": "insertion sort",
    "选择排序": "selection sort",
    "冒泡排序": "bubble sort",
    "希尔排序": "shell sort",
    "计数排序": "counting sort",
    "基数排序": "radix sort",
    "桶排序": "bucket sort",
    "拓扑排序": "topological sort",
    "外部排序": "external sort",
    "并行排序": "parallel sort",
    "线性搜索": "linear search",
    "二分搜索": "binary search",
    "插值搜索": "interpolation search",
    "指数搜索": "exponential search",
    "跳跃搜索": "jump search",
    "三分搜索": "ternary search",
    "斐波那契搜索": "Fibonacci search",
    "深度优先搜索": "depth-first search",
    "广度优先搜索": "breadth-first search",
    "迭代加深搜索": "iterative deepening search",
    "双向搜索": "bidirectional search",
    "A* 搜索": "A* search",
    "Dijkstra 算法": "Dijkstra's algorithm",
    "Bellman-Ford 算法": "Bellman-Ford algorithm",
    "SPFA 算法": "SPFA algorithm",
    "Floyd-Warshall 算法": "Floyd-Warshall algorithm",
    "Johnson 算法": "Johnson's algorithm",
    "Prim 算法": "Prim's algorithm",
    "Kruskal 算法": "Kruskal's algorithm",
    "Boruvka 算法": "Boruvka's algorithm",
    "最大流": "maximum flow",
    "最小割": "minimum cut",
    "Edmonds-Karp 算法": "Edmonds-Karp algorithm",
    "Dinic 算法": "Dinic's algorithm",
    "ISAP 算法": "ISAP algorithm",
    "HLPP 算法": "HLPP algorithm",
    "最小费用最大流": "minimum cost maximum flow",
    "二分图匹配": "bipartite matching",
    "匈牙利算法": "Hungarian algorithm",
    "KM 算法": "KM algorithm",
    "稳定婚姻问题": "stable marriage problem",
    "Gale-Shapley 算法": "Gale-Shapley algorithm",
    "强连通分量": "strongly connected component",
    "Tarjan 算法": "Tarjan's algorithm",
    "Kosaraju 算法": "Kosaraju's algorithm",
    "Gabow 算法": "Gabow's algorithm",
    "双连通分量": "biconnected component",
    "割点": "articulation point",
    "割边": "bridge",
    "欧拉路径": "Eulerian path",
    "欧拉回路": "Eulerian circuit",
    "哈密顿路径": "Hamiltonian path",
    "哈密顿回路": "Hamiltonian circuit",
    "旅行商问题": "traveling salesman problem",
    "最近邻算法": "nearest neighbor algorithm",
    "最小生成树": "minimum spanning tree",
    "斯坦纳树": "Steiner tree",
    "最大独立集": "maximum independent set",
    "最大团": "maximum clique",
    "图着色": "graph coloring",
    "四色定理": "four color theorem",
    "平面图": "planar graph",
    "欧拉图": "Eulerian graph",
    "哈密顿图": "Hamiltonian graph",
    "二分图": "bipartite graph",
    "完全图": "complete graph",
    "有向图": "directed graph",
    "无向图": "undirected graph",
    "加权图": "weighted graph",
    "无权图": "unweighted graph",
    "稀疏图": "sparse graph",
    "稠密图": "dense graph",
    "DAG": "DAG",
    "树": "tree",
    "二叉树": "binary tree",
    "平衡二叉树": "balanced binary tree",
    "AVL 树": "AVL tree",
    "红黑树": "red-black tree",
    "B 树": "B-tree",
    "B+ 树": "B+ tree",
    "B* 树": "B* tree",
    "Trie 树": "Trie tree",
    "后缀树": "suffix tree",
    "线段树": "segment tree",
    "树状数组": "Fenwick tree",
    "并查集": "disjoint set union",
    "哈夫曼树": "Huffman tree",
    "堆": "heap",
    "二叉堆": "binary heap",
    "斐波那契堆": "Fibonacci heap",
    "二项堆": "binomial heap",
    "配对堆": "pairing heap",
    "左偏树": "leftist tree",
    "斜堆": "skew heap",
    "跳表": "skip list",
    "布隆过滤器": "Bloom filter",
    "布谷鸟过滤器": "cuckoo filter",
    "计数布隆过滤器": "counting Bloom filter",
    "可扩展布隆过滤器": "scalable Bloom filter",
    "分布式布隆过滤器": "distributed Bloom filter",
    "一致性哈希": "consistent hashing",
    "Rendezvous 哈希": "Rendezvous hashing",
    "跳跃一致性哈希": "jump consistent hashing",
    "虚拟节点": "virtual node",
    "哈希环": "hash ring",
    "LRU 缓存": "LRU cache",
    "LFU 缓存": "LFU cache",
    "FIFO 缓存": "FIFO cache",
    "时钟算法": "clock algorithm",
    "二次机会算法": "second chance algorithm",
    "老化算法": "aging algorithm",
    "工作集算法": "working set algorithm",
    "WSClock 算法": "WSClock algorithm",
    "最近最少使用": "least recently used",
    "最不经常使用": "least frequently used",
    "先进先出": "first-in-first-out",
    "后进先出": "last-in-first-out",
    
    # Machine Learning
    "机器学习": "machine learning",
    "深度学习": "deep learning",
    "神经网络": "neural network",
    "卷积神经网络": "convolutional neural network",
    "循环神经网络": "recurrent neural network",
    "长短期记忆网络": "LSTM",
    "门控循环单元": "GRU",
    "Transformer": "Transformer",
    "注意力机制": "attention mechanism",
    "自注意力": "self-attention",
    "多头注意力": "multi-head attention",
    "位置编码": "positional encoding",
    "前馈网络": "feed-forward network",
    "残差连接": "residual connection",
    "层归一化": "layer normalization",
    "批归一化": "batch normalization",
    "实例归一化": "instance normalization",
    "组归一化": "group normalization",
    "权重衰减": "weight decay",
    "丢弃法": "dropout",
    "早停": "early stopping",
    "学习率": "learning rate",
    "学习率调度": "learning rate scheduling",
    "优化器": "optimizer",
    "损失函数": "loss function",
    "激活函数": "activation function",
    "反向传播": "backpropagation",
    "梯度下降": "gradient descent",
    "随机梯度下降": "stochastic gradient descent",
    "小批量梯度下降": "mini-batch gradient descent",
    "动量": "momentum",
    "Nesterov 动量": "Nesterov momentum",
    "AdaGrad": "AdaGrad",
    "RMSprop": "RMSprop",
    "Adam": "Adam",
    "AdamW": "AdamW",
    "LAMB": "LAMB",
    "LARS": "LARS",
    "Lookahead": "Lookahead",
    "RAdam": "RAdam",
    "NovoGrad": "NovoGrad",
    "微调": "fine-tuning",
    "迁移学习": "transfer learning",
    "领域适应": "domain adaptation",
    "多任务学习": "multi-task learning",
    "元学习": "meta-learning",
    "少样本学习": "few-shot learning",
    "零样本学习": "zero-shot learning",
    "自监督学习": "self-supervised learning",
    "半监督学习": "semi-supervised learning",
    "无监督学习": "unsupervised learning",
    "监督学习": "supervised learning",
    "强化学习": "reinforcement learning",
    "模仿学习": "imitation learning",
    "对抗学习": "adversarial learning",
    "生成对抗网络": "GAN",
    "变分自编码器": "VAE",
    "自编码器": "autoencoder",
    "去噪自编码器": "denoising autoencoder",
    "稀疏自编码器": "sparse autoencoder",
    "收缩自编码器": "contractive autoencoder",
    "正则化": "regularization",
    "L1 正则化": "L1 regularization",
    "L2 正则化": "L2 regularization",
    "弹性网络": "elastic net",
    "Dropout": "Dropout",
    "DropConnect": "DropConnect",
    "标签平滑": "label smoothing",
    "混合精度训练": "mixed precision training",
    "梯度裁剪": "gradient clipping",
    "梯度累积": "gradient accumulation",
    "分布式训练": "distributed training",
    "数据并行": "data parallelism",
    "模型并行": "model parallelism",
    "流水线并行": "pipeline parallelism",
    "张量并行": "tensor parallelism",
    "专家并行": "expert parallelism",
    "序列并行": "sequence parallelism",
    "ZeRO": "ZeRO",
    "Fully Sharded Data Parallel": "Fully Sharded Data Parallel",
    "DeepSpeed": "DeepSpeed",
    "Megatron-LM": "Megatron-LM",
    "Colossal-AI": "Colossal-AI",
    "FairScale": "FairScale",
    "Horovod": "Horovod",
    "Ray Train": "Ray Train",
    "TorchElastic": "TorchElastic",
    "TorchDynamo": "TorchDynamo",
    "TorchInductor": "TorchInductor",
    "TorchFX": "TorchFX",
    "ONNX": "ONNX",
    "TensorRT": "TensorRT",
    "OpenVINO": "OpenVINO",
    "Core ML": "Core ML",
    "TFLite": "TFLite",
    
    # Generic technical terms
    "项目": "project",
    "系统": "system",
    "程序": "program",
    "应用": "application",
    "软件": "software",
    "硬件": "hardware",
    "固件": "firmware",
    "驱动": "driver",
    "内核": "kernel",
    "操作系统": "operating system",
    "文件系统": "file system",
    "数据库系统": "database system",
    "中间件": "middleware",
    "框架": "framework",
    "库": "library",
    "工具": "tool",
    "平台": "platform",
    "生态": "ecosystem",
    "环境": "environment",
    "运行时": "runtime",
    "编译时": "compile-time",
    "工具链": "toolchain",
    "构建系统": "build system",
    "包管理器": "package manager",
    "依赖管理": "dependency management",
    "版本控制": "version control",
    "持续集成": "CI",
    "持续交付": "CD",
    "持续部署": "continuous deployment",
    "测试驱动开发": "TDD",
    "行为驱动开发": "BDD",
    "领域驱动设计": "DDD",
    "敏捷开发": "agile development",
    "精益开发": "lean development",
    "DevOps": "DevOps",
    "MLOps": "MLOps",
    "DataOps": "DataOps",
    "GitOps": "GitOps",
    "FinOps": "FinOps",
    "SecOps": "SecOps",
    "AIOps": "AIOps",
    "NoOps": "NoOps",
    "低代码": "low-code",
    "无代码": "no-code",
    "声明式": "declarative",
    "命令式": "imperative",
    "函数式": "functional",
    "面向对象": "object-oriented",
    "面向切面": "aspect-oriented",
    "面向服务": "service-oriented",
    "事件驱动": "event-driven",
    "数据驱动": "data-driven",
    "模型驱动": "model-driven",
    "测试驱动": "test-driven",
    "行为驱动": "behavior-driven",
    "领域驱动": "domain-driven",
    "配置驱动": "configuration-driven",
    "策略驱动": "policy-driven",
    "规则驱动": "rule-driven",
    "工作流驱动": "workflow-driven",
    "消息驱动": "message-driven",
    "请求驱动": "request-driven",
    "响应驱动": "response-driven",
    "回调驱动": "callback-driven",
    "Promise 驱动": "Promise-driven",
    "Future 驱动": "Future-driven",
    "Stream 驱动": "Stream-driven",
    "Observable 驱动": "Observable-driven",
    "Reactive 驱动": "Reactive-driven",
    "Actor 驱动": "Actor-driven",
    "CSP 驱动": "CSP-driven",
    "通道驱动": "channel-driven",
    "管道驱动": "pipeline-driven",
    "数据流驱动": "dataflow-driven",
    "控制流驱动": "control flow-driven",
    
    # Short phrases
    "的": "",
    "和": "and",
    "与": "and",
    "或": "or",
    "以及": "and",
    "等": "etc.",
    "中": "in",
    "上": "on",
    "下": "under",
    "前": "before",
    "后": "after",
    "内": "inside",
    "外": "outside",
    "为": "as",
    "将": "will",
    "被": "is",
    "可以": "can",
    "能够": "can",
    "不能": "cannot",
    "必须": "must",
    "应该": "should",
    "可能": "may",
    "如果": "if",
    "当": "when",
    "在": "in",
    "对": "to",
    "从": "from",
    "到": "to",
    "根据": "according to",
    "关于": "about",
    "作为": "as",
    "成为": "become",
    "具有": "has",
    "拥有": "has",
    "本": "this",
    "此": "this",
    "该": "this",
    "其": "its",
    "之": "'s",
    "及": "and",
    "并": "and",
    "且": "and",
    "而": "while",
    "但": "but",
    "却": "but",
    "因": "because",
    "因为": "because",
    "所以": "so",
    "因此": "therefore",
    "于是": "thus",
    "从而": "thereby",
    "进而": "further",
    "然后": "then",
    "接着": "next",
    "随后": "afterwards",
    "最后": "finally",
    "最终": "ultimately",
    "首先": "first",
    "其次": "second",
    "再次": "third",
    "第一": "first",
    "第二": "second",
    "第三": "third",
    "例如": "for example",
    "比如": "for instance",
    "譬如": "such as",
    "像是": "like",
    "类似": "similar to",
    "如同": "as",
    "好比": "like",
    "正如": "just as",
    "就像": "just like",
    "不同于": "different from",
    "区别于": "distinct from",
    "相对于": "relative to",
    "相比于": "compared to",
    "相较于": "compared with",
    "较之": "than",
    "比起": "compared to",
    "与其": "rather than",
    "不如": "not as good as",
    "宁可": "would rather",
    "宁愿": "would rather",
    "最好": "best",
    "最坏": "worst",
    "最大": "maximum",
    "最小": "minimum",
    "最多": "at most",
    "最少": "at least",
    "尽可能": "as much as possible",
    "尽量": "as much as possible",
    "尽量多": "as many as possible",
    "尽量少": "as few as possible",
    "尽量快": "as fast as possible",
    "尽量慢": "as slow as possible",
    "尽量早": "as early as possible",
    "尽量晚": "as late as possible",
    "尽量大": "as large as possible",
    "尽量小": "as small as possible",
    "尽量高": "as high as possible",
    "尽量低": "as low as possible",
    "尽量长": "as long as possible",
    "尽量短": "as short as possible",
    "尽量近": "as close as possible",
    "尽量远": "as far as possible",
    "尽量深": "as deep as possible",
    "尽量浅": "as shallow as possible",
    "尽量宽": "as wide as possible",
    "尽量窄": "as narrow as possible",
    "尽量厚": "as thick as possible",
    "尽量薄": "as thin as possible",
    "尽量重": "as heavy as possible",
    "尽量轻": "as light as possible",
    "尽量强": "as strong as possible",
    "尽量弱": "as weak as possible",
    "尽量硬": "as hard as possible",
    "尽量软": "as soft as possible",
    "尽量热": "as hot as possible",
    "尽量冷": "as cold as possible",
    "尽量干": "as dry as possible",
    "尽量湿": "as wet as possible",
    "尽量干净": "as clean as possible",
    "尽量脏": "as dirty as possible",
    "尽量新": "as new as possible",
    "尽量旧": "as old as possible",
    "尽量好": "as good as possible",
    "尽量坏": "as bad as possible",
    "尽量美": "as beautiful as possible",
    "尽量丑": "as ugly as possible",
    "尽量简单": "as simple as possible",
    "尽量复杂": "as complex as possible",
    "容易": "easy",
    "困难": "difficult",
    "简单": "simple",
    "复杂": "complex",
    "快速": "fast",
    "缓慢": "slow",
    "高效": "efficient",
    "低效": "inefficient",
    "有效": "effective",
    "无效": "ineffective",
    "有用": "useful",
    "无用": "useless",
    "有益": "beneficial",
    "有害": "harmful",
    "有利": "advantageous",
    "有弊": "disadvantageous",
    "优点": "advantage",
    "缺点": "disadvantage",
    "优势": "strength",
    "劣势": "weakness",
    "机会": "opportunity",
    "威胁": "threat",
    "风险": "risk",
    "挑战": "challenge",
    "问题": "problem",
    "解决方案": "solution",
    "答案": "answer",
    "结果": "result",
    "效果": "effect",
    "影响": "impact",
    "作用": "role",
    "功能": "functionality",
    "用途": "purpose",
    "目标": "goal",
    "目的": "objective",
    "意图": "intention",
    "计划": "plan",
    "策略": "strategy",
    "战术": "tactic",
    "方法": "method",
    "方式": "way",
    "途径": "approach",
    "手段": "means",
    "技术": "technique",
    "技能": "skill",
    "技巧": "tip",
    "诀窍": "trick",
    "秘密": "secret",
    "关键": "key",
    "核心": "core",
    "本质": "essence",
    "实质": "substance",
    "基础": "foundation",
    "根本": "root",
    "根源": "source",
    "起源": "origin",
    "出处": "source",
    "引用": "reference",
    "参考": "reference",
    "借鉴": "draw on",
    "学习": "learn",
    "研究": "research",
    "调查": "investigate",
    "分析": "analyze",
    "综合": "synthesize",
    "归纳": "induce",
    "演绎": "deduce",
    "推理": "reason",
    "推断": "infer",
    "推测": "speculate",
    "猜测": "guess",
    "假设": "hypothesize",
    "假定": "assume",
    "设想": "envision",
    "想象": "imagine",
    "构思": "conceive",
    "设计": "design",
    "规划": "plan",
    "布局": "layout",
    "安排": "arrange",
    "组织": "organize",
    "结构": "structure",
    "架构": "architecture",
    "体系": "system",
    "机制": "mechanism",
    "体制": "mechanism",
    "制度": "institution",
    "规则": "rule",
    "规范": "specification",
    "标准": "standard",
    "准则": "guideline",
    "原则": "principle",
    "定律": "law",
    "定理": "theorem",
    "公理": "axiom",
    "定义": "definition",
    "概念": "concept",
    "观念": "notion",
    "理念": "philosophy",
    "思想": "thought",
    "理论": "theory",
    "学说": "doctrine",
    "主义": "ism",
    "观点": "viewpoint",
    "看法": "view",
    "态度": "attitude",
    "立场": "stance",
    "角度": "angle",
    "视角": "perspective",
    "维度": "dimension",
    "层面": "level",
    "层次": "hierarchy",
    "等级": "grade",
    "级别": "level",
    "阶段": "stage",
    "时期": "period",
    "时代": "era",
    "年代": "decade",
    "年份": "year",
    "月份": "month",
    "日期": "date",
    "时间": "time",
    "时刻": "moment",
    "瞬间": "instant",
    "片刻": "moment",
    "刹那": "instant",
    "永恒": "eternity",
    "永久": "permanent",
    "临时": "temporary",
    "暂时": "temporary",
    "短期": "short-term",
    "长期": "long-term",
    "中期": "medium-term",
    "近期": "near-term",
    "远期": "far-term",
    "过去": "past",
    "现在": "present",
    "将来": "future",
    "未来": "future",
    "前景": "prospect",
    "前途": "future",
    "背景": "background",
    "前景": "foreground",
    "场景": "scenario",
    "情景": "scene",
    "情况": "situation",
    "状况": "condition",
    "状态": "state",
    "情形": "circumstance",
    "环境": "environment",
    "条件": "condition",
    "前提": "prerequisite",
    "依据": "basis",
    "理由": "reason",
    "原因": "cause",
    "因果": "cause and effect",
    "后果": "consequence",
    "效率": "efficiency",
    "效益": "benefit",
    "收益": "return",
    "利润": "profit",
    "损失": "loss",
    "成本": "cost",
    "费用": "expense",
    "开销": "overhead",
    "支出": "expenditure",
    "投资": "investment",
    "回报": "return",
    "价值": "value",
    "价格": "price",
    "代价": "price",
    "质量": "quality",
    "数量": "quantity",
    "规模": "scale",
    "范围": "scope",
    "程度": "degree",
    "水平": "level",
    "规范": "norm",
    "准则": "criterion",
    "指标": "indicator",
    "指数": "index",
    "系数": "coefficient",
    "因子": "factor",
    "因素": "factor",
    "要素": "element",
    "元素": "element",
    "成分": "component",
    "组成部分": "component",
    "部分": "part",
    "局部": "local",
    "整体": "whole",
    "全局": "global",
    "总体": "overall",
    "全部": "all",
    "全体": "all",
    "完整": "complete",
    "完美": "perfect",
    "理想": "ideal",
    "现实": "realistic",
    "实际": "actual",
    "真实": "real",
    "虚假": "false",
    "伪装": "disguise",
    "掩饰": "conceal",
    "隐藏": "hide",
    "暴露": "expose",
    "揭示": "reveal",
    "展现": "show",
    "显示": "display",
    "表示": "represent",
    "表达": "express",
    "表述": "formulate",
    "描述": "describe",
    "叙述": "narrate",
    "讲述": "tell",
    "说明": "explain",
    "解释": "explain",
    "阐释": "elucidate",
    "阐明": "clarify",
    "澄清": "clarify",
    "明确": "explicit",
    "清楚": "clear",
    "模糊": "vague",
    "清晰": "clear",
    "明显": "obvious",
    "显著": "significant",
    "重要": "important",
    "次要": "secondary",
    "主要": "main",
    "关键": "key",
    "中心": "center",
    "焦点": "focus",
    "重点": "emphasis",
    "要点": "main point",
    "要领": "essentials",
    "大纲": "outline",
    "摘要": "summary",
    "总结": "summary",
    "概括": "generalize",
    "归纳": "summarize",
    "综述": "review",
    "回顾": "review",
    "展望": "outlook",
    "预测": "forecast",
    "预报": "forecast",
    "预警": "early warning",
    "警报": "alert",
    "警告": "warning",
    "提醒": "reminder",
    "提示": "hint",
    "暗示": "hint",
    "示意": "indicate",
    "表明": "indicate",
    "标志": "mark",
    "标记": "mark",
    "符号": "symbol",
    "记号": "notation",
    "代号": "code name",
    "编号": "number",
    "序号": "serial number",
    "顺序": "order",
    "序列": "sequence",
    "排列": "arrangement",
    "排序": "ordering",
    "分类": "classification",
    "归类": "categorization",
    "分组": "grouping",
    "分区": "partitioning",
    "分段": "segmentation",
    "分层": "layering",
    "分级": "grading",
    "分片": "sharding",
    "分解": "decomposition",
    "合成": "synthesis",
    "组合": "combination",
    "整合": "integration",
    "聚合": "aggregation",
    "集合": "collection",
    "聚集": "gathering",
    "分散": "dispersion",
    "分布": "distribution",
    "扩散": "diffusion",
    "传播": "propagation",
    "传导": "conduction",
    "传输": "transmission",
    "转移": "transfer",
    "转化": "transformation",
    "转变": "transition",
    "变换": "transformation",
    "转换": "conversion",
    "切换": "switching",
    "交换": "exchange",
    "交替": "alternation",
    "轮换": "rotation",
    "循环": "circulation",
    "周转": "turnover",
    "流通": "circulation",
    "流动": "flow",
    "流量": "flow rate",
    "流速": "flow velocity",
    "流向": "flow direction",
    "流程": "process",
    "工序": "procedure",
    "步骤": "step",
    "环节": "link",
    "节点": "node",
    "顶点": "vertex",
    "边": "edge",
    "面": "face",
    "体": "volume",
    "点": "point",
    "线": "line",
    "面": "surface",
    "空间": "space",
    "时空": "spacetime",
    "坐标": "coordinate",
    "轴": "axis",
    "原点": "origin",
    "方向": "direction",
    "方位": "orientation",
    "位置": "position",
    "地点": "location",
    "区域": "area",
    "区间": "interval",
    "域": "domain",
    "集合": "set",
    "子集": "subset",
    "超集": "superset",
    "交集": "intersection",
    "并集": "union",
    "差集": "difference set",
    "补集": "complement set",
    "笛卡尔积": "Cartesian product",
    "幂集": "power set",
    "空集": "empty set",
    "全集": "universal set",
    "有限集": "finite set",
    "无限集": "infinite set",
    "可数集": "countable set",
    "不可数集": "uncountable set",
    "开集": "open set",
    "闭集": "closed set",
    "紧致集": "compact set",
    "连通集": "connected set",
    "凸集": "convex set",
    "线性空间": "linear space",
    "向量空间": "vector space",
    "赋范空间": "normed space",
    "巴拿赫空间": "Banach space",
    "希尔伯特空间": "Hilbert space",
    "内积空间": "inner product space",
    "度量空间": "metric space",
    "拓扑空间": "topological space",
    "流形": "manifold",
    "切空间": "tangent space",
    "余切空间": "cotangent space",
    "张量": "tensor",
    "张量积": "tensor product",
    "外积": "outer product",
    "内积": "inner product",
    "点积": "dot product",
    "叉积": "cross product",
    "楔积": "wedge product",
    "张量缩并": "tensor contraction",
    "张量场": "tensor field",
    "向量场": "vector field",
    "标量场": "scalar field",
    "梯度": "gradient",
    "散度": "divergence",
    "旋度": "curl",
    "拉普拉斯算子": "Laplacian",
    "达朗贝尔算子": "d'Alembertian",
    "偏导数": "partial derivative",
    "全导数": "total derivative",
    "方向导数": "directional derivative",
    "变分": "variation",
    "泛函": "functional",
    "欧拉-拉格朗日方程": "Euler-Lagrange equation",
    "哈密顿量": "Hamiltonian",
    "拉格朗日量": "Lagrangian",
    "泊松括号": "Poisson bracket",
    "对易子": "commutator",
    "反对易子": "anticommutator",
    "李括号": "Lie bracket",
    "李导数": "Lie derivative",
    "外微分": "exterior derivative",
    "霍奇星算子": "Hodge star operator",
    "德拉姆上同调": "de Rham cohomology",
    "切丛": "tangent bundle",
    "余切丛": "cotangent bundle",
    "向量丛": "vector bundle",
    "主丛": "principal bundle",
    "联络": "connection",
    "曲率": "curvature",
    "挠率": "torsion",
    "和乐群": "holonomy group",
    "示性类": "characteristic class",
    "陈类": "Chern class",
    "庞特里亚金类": "Pontryagin class",
    "欧拉类": "Euler class",
    "斯蒂费尔-惠特尼类": "Stiefel-Whitney class",
    "指标定理": "index theorem",
    "阿蒂亚-辛格指标定理": "Atiyah-Singer index theorem",
    "热核": "heat kernel",
    "狄拉克算子": "Dirac operator",
    "狄拉克方程": "Dirac equation",
    "克莱因-戈登方程": "Klein-Gordon equation",
    "麦克斯韦方程组": "Maxwell's equations",
    "爱因斯坦场方程": "Einstein field equations",
    "薛定谔方程": "Schrödinger equation",
    "海森堡绘景": "Heisenberg picture",
    "薛定谔绘景": "Schrödinger picture",
    "相互作用绘景": "interaction picture",
    "密度矩阵": "density matrix",
    "路径积分": "path integral",
    "费曼图": "Feynman diagram",
    "重整化": "renormalization",
    "正规化": "regularization",
    "维数正规化": "dimensional regularization",
    "泡利不相容原理": "Pauli exclusion principle",
    "海森堡不确定性原理": "Heisenberg uncertainty principle",
    "贝尔不等式": "Bell's inequality",
    "量子纠缠": "quantum entanglement",
    "量子叠加": "quantum superposition",
    "量子退相干": "quantum decoherence",
    "量子纠错": "quantum error correction",
    "拓扑量子计算": "topological quantum computing",
    "量子比特": "qubit",
    "量子门": "quantum gate",
    "量子电路": "quantum circuit",
    "量子傅里叶变换": "quantum Fourier transform",
    "肖尔算法": "Shor's algorithm",
    "格罗弗算法": "Grover's algorithm",
    "量子模拟": "quantum simulation",
    "量子机器学习": "quantum machine learning",
    "量子神经网络": "quantum neural network",
    "量子支持向量机": "quantum SVM",
    "量子主成分分析": "quantum PCA",
    "量子聚类": "quantum clustering",
    "量子强化学习": "quantum reinforcement learning",
    "量子生成对抗网络": "quantum GAN",
    "量子变分算法": "quantum variational algorithm",
    "量子近似优化算法": "QAOA",
    "变分量子特征求解器": "VQE",
}

# Sort keys by length descending for greedy matching
SORTED_KEYS = sorted(TRANSLATIONS.keys(), key=len, reverse=True)


def translate_with_spaces(text):
    """Translate Chinese text to English with proper spacing."""
    result = []
    i = 0
    n = len(text)
    
    while i < n:
        matched = False
        # Try to match the longest possible phrase
        for key in SORTED_KEYS:
            if i + len(key) <= n and text[i:i+len(key)] == key:
                translation = TRANSLATIONS[key]
                if translation:  # Skip empty translations (like "的" -> "")
                    result.append(translation)
                    result.append(' ')
                i += len(key)
                matched = True
                break
        
        if not matched:
            ch = text[i]
            # If it's a Chinese character, skip it (untranslated)
            if '\u4e00' <= ch <= '\u9fff':
                i += 1
                continue
            # Otherwise keep non-Chinese characters as-is
            result.append(ch)
            i += 1
    
    # Clean up: remove extra spaces, but keep single spaces
    translated = ''.join(result)
    # Replace multiple spaces with single space
    translated = re.sub(r' +', ' ', translated)
    # Remove spaces before punctuation
    translated = re.sub(r' ([,;.!?])', r'\1', translated)
    translated = translated.strip()
    
    return translated


def translate_line(line):
    """Translate a Chinese doc comment line to English."""
    match = re.match(r'^(\s*(?:///|//!)\s*)(.*)$', line)
    if not match:
        return None
    
    prefix = match.group(1)
    text = match.group(2)
    
    if not text.strip():
        return None
    
    # If no Chinese characters, skip
    if not re.search(r'[\u4e00-\u9fff]', text):
        return None
    
    # Skip lines that are mostly English already
    english_chars = len(re.findall(r'[a-zA-Z]', text))
    chinese_chars = len(re.findall(r'[\u4e00-\u9fff]', text))
    if english_chars > chinese_chars * 2:
        return None
    
    translated = translate_with_spaces(text)
    
    # If translation is empty or too similar to original, skip
    if not translated or translated == text:
        return None
    
    # If still has too much Chinese, skip
    remaining_chinese = len(re.findall(r'[\u4e00-\u9fff]', translated))
    if remaining_chinese > 0:
        # Some Chinese left - check ratio
        total_chars = len(re.sub(r'\s', '', translated))
        if remaining_chinese / max(total_chars, 1) > 0.15:
            return None
    
    return prefix + translated


def process_file(filepath):
    """Process a single Rust file."""
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    new_lines = []
    modified = False
    
    for line in lines:
        line_stripped = line.rstrip('\n')
        
        if re.match(r'^\s*(///|//!)', line_stripped) and re.search(r'[\u4e00-\u9fff]', line_stripped):
            translated = translate_line(line_stripped)
            new_lines.append(line_stripped)
            if translated and translated != line_stripped:
                new_lines.append(translated)
                modified = True
        else:
            new_lines.append(line_stripped)
    
    if modified:
        with open(filepath, 'w', encoding='utf-8') as f:
            for line in new_lines:
                f.write(line + '\n')
    
    return modified


def main():
    target_dirs = [
        'crates/c02_type_system',
        'crates/c03_control_fn',
        'crates/c04_generic',
        'crates/c05_threads',
        'crates/c06_async',
        'crates/c07_process',
        'crates/c08_algorithms',
        'crates/c09_design_pattern',
        'crates/c10_networks',
        'crates/c11_macro_system',
        'crates/c11_macro_system_proc',
        'crates/c12_wasm',
        'crates/c13_embedded',
        'crates/exercises',
        'examples',
    ]
    
    candidates = []
    for target in target_dirs:
        if not os.path.exists(target):
            continue
        for root, dirs, files in os.walk(target):
            dirs[:] = [d for d in dirs if d != 'target']
            for file in files:
                if file.endswith('.rs'):
                    filepath = os.path.join(root, file)
                    candidates.append(filepath)
    
    modified_files = []
    for filepath in candidates:
        if process_file(filepath):
            modified_files.append(filepath)
    
    print(f"Modified {len(modified_files)} files")


if __name__ == '__main__':
    main()
