#!/usr/bin/env python3
"""Add English translations to Chinese doc comments in Rust source files."""

import os
import re

EXACT = {
    "# 参数": "# Arguments", "# 返回": "# Returns", "# 示例": "# Examples",
    "# 返回值": "# Return Value", "# 注意": "# Notes", "# 安全": "# Safety",
    "# 性能": "# Performance", "# 约束": "# Constraints", "# 限制": "# Limitations",
    "# 版本信息": "# Version Information", "# 文件信息": "# File Information",
    "# 类型参数": "# Type Parameters", "# 生命周期参数": "# Lifetime Parameters",
    "# 前置条件": "# Preconditions", "# 后置条件": "# Postconditions",
    "# 错误": "# Errors", "# 警告": "# Warnings", "# 提示": "# Tips",
    "# 说明": "# Description", "# 概述": "# Overview", "# 详情": "# Details",
    "# 参考": "# References", "# 相关": "# Related", "# 另见": "# See Also",
    "# 兼容性": "# Compatibility", "# 历史": "# History", "# 变更": "# Changes",
    "# 实现": "# Implementation", "# 设计": "# Design", "# 架构": "# Architecture",
    "# 模块": "# Module", "# 结构体": "# Struct", "# 枚举": "# Enum",
    "# 特征": "# Trait", "# 函数": "# Function", "# 方法": "# Methods",
    "# 常量": "# Constants", "# 变量": "# Variables", "# 字段": "# Fields",
    "# 属性": "# Attributes", "# 泛型": "# Generics", "# 特化": "# Specialization",
    "# 多态": "# Polymorphism", "# 类型": "# Types", "# 值": "# Values",
    "# 表达式": "# Expressions", "# 语句": "# Statements", "# 块": "# Blocks",
    "# 模式": "# Patterns", "# 匹配": "# Match", "# 控制流": "# Control Flow",
    "# 循环": "# Loops", "# 条件": "# Conditions", "# 分支": "# Branches",
    "# 跳转": "# Jumps", "# 异常": "# Exceptions", "# 错误处理": "# Error Handling",
    "# 异步": "# Async", "# 并发": "# Concurrency", "# 并行": "# Parallelism",
    "# 同步": "# Synchronization", "# 线程": "# Threads", "# 进程": "# Processes",
    "# 内存": "# Memory", "# 所有权": "# Ownership", "# 借用": "# Borrowing",
    "# 生命周期": "# Lifetimes", "# 引用": "# References", "# 指针": "# Pointers",
    "# 智能指针": "# Smart Pointers", "# 原始指针": "# Raw Pointers",
    "# 闭包": "# Closures", "# 迭代器": "# Iterators", "# 流": "# Streams",
    "# 通道": "# Channels", "# 锁": "# Locks", "# 原子操作": "# Atomic Operations",
    "# 无锁": "# Lock-free", "# 屏障": "# Barriers", "# 信号量": "# Semaphores",
    "# 条件变量": "# Condition Variables", "# 线程本地存储": "# Thread-local Storage",
    "# 线程池": "# Thread Pool", "# 工作窃取": "# Work Stealing",
    "# 作用域线程": "# Scoped Threads", "# 生成器": "# Generators",
    "# 协程": "# Coroutines", "## 使用场景": "## Use Cases", "## 限制": "## Limitations",
    "## 现在": "## Now", "## 语法": "## Syntax", "## 版本历史说明": "## Version History",
    "## 背景": "## Background", "## 影响": "## Impact", "## 1.95 方式": "## 1.95 Approach",
    "## 1.95 之前": "## Before 1.95", "## 之前": "## Before",
    "## 概念定义": "## Concept Definition", "## 对比": "## Comparison",
    "## 反例 / 限制": "## Counter-examples / Limitations",
    "## Wikipedia 概念对齐": "## Wikipedia Concept Alignment",
    "## 声明方式": "## Declaration Style", "## 实践意义": "## Practical Significance",
    "## 对现有代码的影响": "## Impact on Existing Code",
    "## 对 Cargo.toml 的影响": "## Impact on Cargo.toml",
    "## 对 Workspace 的影响": "## Impact on Workspace",
    "## 验证当前链接器": "## Verify Current Linker",
    "## 验证发布顺序": "## Verify Publish Order",
    "## 交叉编译对比": "## Cross-compilation Comparison",
    "### 迁移建议": "### Migration Suggestions",
    "### Rust 1.92.0 主要改进": "### Rust 1.92.0 Major Improvements",
    "# 数学定义": "# Mathematical Definition", "# 特性说明": "# Feature Description",
    "# Rust 1.89 特性示例 (历史版本)": "# Rust 1.89 Feature Examples (Historical Version)",
    "# 跨平台泛型特化": "# Cross-platform Generic Specialization",
    "# 泛型配置解析": "# Generic Configuration Parsing",
    "# 泛型算法中的条件模式匹配": "# Conditional Pattern Matching in Generic Algorithms",
    "# `if let` Guards 深度解析": "# Deep Dive into `if let` Guards",
    "# `Atomic*::update` / `try_update` 深度解析": "# Deep Dive into `Atomic*::update` / `try_update`",
    "# `cfg_select!` 与泛型特化": "# `cfg_select!` and Generic Specialization",
    "# 发布特定包及其依赖": "# Publish Specific Package and Its Dependencies",
    "# 发布 workspace 中的所有包": "# Publish All Packages in Workspace",
    "# Let Chains 稳定化": "# Let Chains Stabilization",
    "# C 风格变参函数（C Variadic Functions）": "# C-style Variadic Functions",
    "# 安全函数的 `#[target_feature]`": "# `#[target_feature]` on Safe Functions",
    "# `MaybeUninit` 文档化保证": "# `MaybeUninit` Documentation Guarantees",
    "# 模型检查属性": "# Model Checking Attributes",
    "# 显式推断 const 参数": "# Explicit Inferred Const Parameters",
    "# x86_64 默认使用 LLD 链接器": "# x86_64 Default LLD Linker",
    "# `aarch64-pc-windows-msvc` 晋升 Tier 1": "# `aarch64-pc-windows-msvc` Promoted to Tier 1",
    "# 归档的历史版本特性模块": "# Archived Historical Version Features Module",
    "# Trait 对象向上转换": "# Trait Object Upcasting",
    "# Cargo 多包发布（Multi-Package Publishing）": "# Cargo Multi-Package Publishing",
    "# Safe 代码中的 `&raw` 联合体字段引用": "# `&raw` Union Field References in Safe Code",
    "# 核心概念": "# Core Concepts", "# 核心特性": "# Core Features",
    "# 核心结构": "# Core Structures", "# 核心方法": "# Core Methods",
    "# 核心类型": "# Core Types", "# 核心函数": "# Core Functions",
    "# 核心模块": "# Core Modules", "# 核心 trait": "# Core Traits",
    "# 核心实现": "# Core Implementation", "# 核心设计": "# Core Design",
    "# 核心架构": "# Core Architecture", "# 核心模式": "# Core Patterns",
    "# 核心算法": "# Core Algorithms", "# 核心数据结构": "# Core Data Structures",
    "# 核心工具": "# Core Utilities", "# 核心配置": "# Core Configuration",
    "# 核心参数": "# Core Parameters", "# 核心选项": "# Core Options",
    "# 核心状态": "# Core State", "# 核心行为": "# Core Behavior",
    "# 核心逻辑": "# Core Logic", "# 核心流程": "# Core Flow",
    "# 核心步骤": "# Core Steps", "# 核心阶段": "# Core Stages",
    "# 核心要点": "# Core Points", "# 核心细节": "# Core Details",
    "# 核心技巧": "# Core Tips", "# 核心注意": "# Core Notes",
    "# 核心警告": "# Core Warnings", "# 核心错误": "# Core Errors",
    "# 核心问题": "# Core Issues", "# 核心风险": "# Core Risks",
    "# 核心挑战": "# Core Challenges", "# 核心难点": "# Core Difficulties",
    "# 核心解决方案": "# Core Solutions", "# 核心优化": "# Core Optimizations",
    "# 核心改进": "# Core Improvements", "# 核心增强": "# Core Enhancements",
    "# 核心扩展": "# Core Extensions", "# 核心定制": "# Core Customizations",
    "# 核心适配": "# Core Adaptations", "# 核心集成": "# Core Integrations",
    "# 核心测试": "# Core Tests", "# 核心验证": "# Core Validation",
    "# 核心确认": "# Core Verification", "# 核心检查": "# Core Checks",
    "# 核心审查": "# Core Reviews", "# 核心审计": "# Core Audits",
    "# 核心分析": "# Core Analysis", "# 核心评估": "# Core Evaluation",
    "# 核心度量": "# Core Metrics", "# 核心指标": "# Core Indicators",
    "# 核心监控": "# Core Monitoring", "# 核心告警": "# Core Alerts",
    "# 核心日志": "# Core Logging", "# 核心追踪": "# Core Tracing",
    "# 核心调试": "# Core Debugging", "# 核心诊断": "# Core Diagnostics",
    "# 核心修复": "# Core Fixes", "# 核心补丁": "# Core Patches",
    "# 核心更新": "# Core Updates", "# 核心升级": "# Core Upgrades",
    "# 核心降级": "# Core Downgrades", "# 核心迁移": "# Core Migrations",
    "# 核心转换": "# Core Conversions", "# 核心变换": "# Core Transformations",
    "# 核心映射": "# Core Mappings", "# 核心投影": "# Core Projections",
    "# 核心过滤": "# Core Filtering", "# 核心排序": "# Core Sorting",
    "# 核心搜索": "# Core Searching", "# 核心查找": "# Core Lookup",
    "# 核心匹配": "# Core Matching", "# 核心替换": "# Core Replacement",
    "# 核心插入": "# Core Insertion", "# 核心删除": "# Core Deletion",
    "# 核心添加": "# Core Addition", "# 核心移除": "# Core Removal",
    "# 核心清空": "# Core Clearing", "# 核心重置": "# Core Resetting",
    "# 核心启动": "# Core Startup", "# 核心停止": "# Core Shutdown",
    "# 核心暂停": "# Core Pausing", "# 核心恢复": "# Core Resuming",
    "# 核心重启": "# Core Restarting", "# 核心创建": "# Core Creation",
    "# 核心销毁": "# Core Destruction", "# 核心分配": "# Core Allocation",
    "# 核心释放": "# Core Deallocation", "# 核心复制": "# Core Copying",
    "# 核心克隆": "# Core Cloning", "# 核心移动": "# Core Moving",
    "# 核心推送": "# Core Pushing", "# 核心弹出": "# Core Popping",
    "# 核心压入": "# Core Pushing", "# 核心查看": "# Core Viewing",
    "# 核心访问": "# Core Accessing", "# 核心修改": "# Core Modifying",
    "# 核心增加": "# Core Increasing", "# 核心减少": "# Core Decreasing",
    "# 核心自增": "# Core Incrementing", "# 核心自减": "# Core Decrementing",
    "# 核心乘以": "# Core Multiplying", "# 核心除以": "# Core Dividing",
    "# 核心取模": "# Core Modulo", "# 核心取整": "# Core Rounding",
    "# 核心向上取整": "# Core Ceiling", "# 核心向下取整": "# Core Flooring",
    "# 核心四舍五入": "# Core Rounding", "# 核心绝对值": "# Core Absolute Value",
    "# 核心最大值": "# Core Maximum", "# 核心最小值": "# Core Minimum",
    "# 核心求和": "# Core Sum", "# 核心平均值": "# Core Average",
    "# 核心中位数": "# Core Median", "# 核心哈希": "# Core Hashing",
    "# 核心编码": "# Core Encoding", "# 核心解码": "# Core Decoding",
    "# 核心序列化": "# Core Serialization", "# 核心反序列化": "# Core Deserialization",
    "# 核心压缩": "# Core Compression", "# 核心解压": "# Core Decompression",
    "# 核心加密": "# Core Encryption", "# 核心解密": "# Core Decryption",
    "# 核心签名": "# Core Signing", "# 核心验证签名": "# Core Signature Verification",
    "# 核心摘要": "# Core Digest", "# 核心随机": "# Core Randomization",
    "# 核心洗牌": "# Core Shuffling", "# 核心采样": "# Core Sampling",
    "# 核心抽样": "# Core Sampling", "# 核心测试": "# Core Testing",
    "# 核心基准测试": "# Core Benchmarking", "# 核心性能测试": "# Core Performance Testing",
    "# 核心压力测试": "# Core Stress Testing", "# 核心模糊测试": "# Core Fuzz Testing",
    "# 核心单元测试": "# Core Unit Testing", "# 核心集成测试": "# Core Integration Testing",
    "# 核心端到端测试": "# Core End-to-end Testing", "# 核心文档测试": "# Core Doc Testing",
    "# 编译时": "# Compile-time", "# 运行时": "# Runtime",
    "# 类型安全的": "# Type-safe", "# 零开销": "# Zero-cost",
    "# 泛型": "# Generic", "# 特化": "# Specialized",
    "# 动态分发": "# Dynamic Dispatch", "# 静态分发": "# Static Dispatch",
    "# 单态化": "# Monomorphization", "# 虚表": "# Vtable",
    "# 特征对象": "# Trait Object", "# 关联类型": "# Associated Type",
    "# 常量泛型": "# Const Generic", "# 默认实现": "# Default Implementation",
    "# 泛型约束": "# Generic Constraints", "# 类型转换": "# Type Conversion",
    "# 类型强制": "# Type Coercion", "# 类型造型": "# Type Casting",
    "# 类型别名": "# Type Alias", "# 新类型": "# Newtype",
    "# 不透明类型": "# Opaque Type", "# 透明类型": "# Transparent Type",
    "# 具体类型": "# Concrete Type", "# 抽象类型": "# Abstract Type",
    "# 存在类型": "# Existential Type", "# 名义类型": "# Nominal Type",
    "# 结构类型": "# Structural Type", "# 静态类型": "# Static Typing",
    "# 动态类型": "# Dynamic Typing", "# 强类型": "# Strong Typing",
    "# 弱类型": "# Weak Typing", "# 显式类型": "# Explicit Typing",
    "# 隐式类型": "# Implicit Typing", "# Send": "# Send", "# Sync": "# Sync",
    "# Copy": "# Copy", "# Clone": "# Clone", "# Default": "# Default",
    "# Debug": "# Debug", "# Display": "# Display", "# Eq": "# Eq",
    "# PartialEq": "# PartialEq", "# Ord": "# Ord", "# PartialOrd": "# PartialOrd",
    "# Hash": "# Hash", "# Drop": "# Drop", "# Fn": "# Fn",
    "# FnOnce": "# FnOnce", "# FnMut": "# FnMut", "# From": "# From",
    "# Into": "# Into", "# TryFrom": "# TryFrom", "# TryInto": "# TryInto",
    "# AsRef": "# AsRef", "# AsMut": "# AsMut", "# Deref": "# Deref",
    "# DerefMut": "# DerefMut", "# Index": "# Index", "# IndexMut": "# IndexMut",
    "# Iterator": "# Iterator", "# IntoIterator": "# IntoIterator",
    "# ExactSizeIterator": "# ExactSizeIterator", "# DoubleEndedIterator": "# DoubleEndedIterator",
    "# FusedIterator": "# FusedIterator", "# Extend": "# Extend",
    "# FromIterator": "# FromIterator", "# Product": "# Product", "# Sum": "# Sum",
    "# Add": "# Add", "# Sub": "# Sub", "# Mul": "# Mul", "# Div": "# Div",
    "# Rem": "# Rem", "# Neg": "# Neg", "# Not": "# Not",
    "# BitAnd": "# BitAnd", "# BitOr": "# BitOr", "# BitXor": "# BitXor",
    "# Shl": "# Shl", "# Shr": "# Shr", "# AddAssign": "# AddAssign",
    "# SubAssign": "# SubAssign", "# MulAssign": "# MulAssign",
    "# DivAssign": "# DivAssign", "# RemAssign": "# RemAssign",
    "# BitAndAssign": "# BitAndAssign", "# BitOrAssign": "# BitOrAssign",
    "# BitXorAssign": "# BitXorAssign", "# ShlAssign": "# ShlAssign",
    "# ShrAssign": "# ShrAssign",
    "获取值": "Gets the value", "参考:": "Reference:",
    "// 归档模块示例": "// Archived module example",
    "检查数组是否为空": "Checks if the array is empty",
    "检查是否已初始化": "Checks if initialized",
    "检查是否为空": "Checks if empty",
    "尝试推送元素": "Attempts to push an element",
    "接收消息": "Receives a message",
    "综合演示函数": "Comprehensive demonstration function",
    "调用者必须确保：": "The caller must ensure:",
    "插入键值对": "Inserts a key-value pair",
    "尝试弹出元素": "Attempts to pop an element",
    "获取元数据": "Gets metadata", "获取数组长度": "Gets the array length",
    "获取元素": "Gets an element", "设置值": "Sets the value",
    "获取数据引用": "Gets a data reference", "获取数据": "Gets data",
    "处理数据": "Processes data", "设置元素": "Sets an element",
    "运行示例": "Run example", "运行方式:": "How to run:",
    "用法：": "Usage:", "使用示例和测试": "Usage examples and tests",
    "预期结果: Miri 应该检测到 UB": "Expected result: Miri should detect UB",
    "预期结果: 应该正确读写值": "Expected result: Should read and write values correctly",
    "错误类型": "Error type", "编译时常量": "Compile-time constant",
    "内部数组数据": "Internal array data",
    "返回较长的引用": "Returns the longer reference",
    "返回连接后的字符串": "Returns the concatenated string",
    "返回编译时确定的数组长度N。": "Returns the compile-time determined array length N.",
    "返回新创建的ConstGenericArray实例": "Returns a new ConstGenericArray instance",
    "返回指定索引的元素引用": "Returns a reference to the element at the specified index",
    "如果索引超出范围则panic": "Panics if the index is out of bounds",
    "此方法在编译时优化为常量，无运行时开销。": "This method is optimized to a constant at compile time with no runtime overhead.",
    "如果设置成功返回Some(())，否则返回None": "Returns Some(()) if the setting succeeds, otherwise returns None",
    "因为调用未启用对应特性的函数是 UB。": "Because calling a function without the corresponding feature enabled is UB.",
    "使用 C ABI 与 C 的 `...` 语法兼容。": "Uses C ABI compatible with C's `...` syntax.",
    "第一个生命周期受限的数据": "First lifetime-restricted data",
    "获取联合体字段的原始指针，而无需 `unsafe` 块。": "Gets a raw pointer to the union field without an `unsafe` block.",
    "在 safe 代码中读取联合体字节表示": "Reads union byte representation in safe code",
    "数组长度，类型为usize": "Array length, type usize",
    "以下代码需要 nightly 工具链才能编译。": "The following code requires a nightly toolchain to compile.",
    "包括类型安全、性能优化、错误处理等最佳实践。": "Includes best practices for type safety, performance optimization, error handling, etc.",
    "本文件展示 Rust 1.89 版本的特性，当前项目已升级到 Rust 1.92.0。": "This file shows Rust 1.89 features; the project has been upgraded to Rust 1.92.0.",
    "**当前推荐版本**: Rust 1.92.0+ | 最新特性请参考 `rust_192_features.rs`": "**Current recommended version**: Rust 1.92.0+ | For latest features, see `rust_192_features.rs`",
    "⚠️ **历史版本文件** - 本文件仅作为历史参考保留": "⚠️ **Historical version file** - This file is kept for historical reference only",
    "- 版本: 1.0": "- Version: 1.0",
    "- 创建日期: 2025-01-27": "- Creation date: 2025-01-27",
    "- 创建日期: 2026-03-06": "- Creation date: 2026-03-06",
    "- 创建日期: 2025-12-11": "- Creation date: 2025-12-11",
    "- `index`: 元素索引": "- `index`: Element index",
    "- `value`: 要包装的值": "- `value`: The value to wrap",
    "- `col`: 列索引": "- `col`: Column index",
    "- `row`: 行索引": "- `row`: Row index",
    "- 作者: Rust 类型系统项目组": "- Author: Rust Type System Project Team",
    "- `value`: 要设置的值": "- `value`: The value to set",
    "- 完整的示例和测试用例": "- Complete examples and test cases",
    "- 性能优化技巧": "- Performance optimization tips",
    "- `metadata`: 第二个生命周期受限的元数据": "- `metadata`: The second lifetime-restricted metadata",
    "- Rust版本: 1.89.0": "- Rust version: 1.89.0",
    "- Rust版本: 1.90.0": "- Rust version: 1.90.0",
    "- Rust版本: 1.92.0": "- Rust version: 1.92.0",
    "- Rust版本: 1.94.0": "- Rust version: 1.94.0",
    "- Rust版本: 1.95.0": "- Rust version: 1.95.0",
    "- Rust 版本: 186.0": "- Rust version: 186.0",
    "- Rust 版本: 187.0": "- Rust version: 187.0",
    "- Rust 版本: 188.0": "- Rust version: 188.0",
    "- Rust 版本: 189.0": "- Rust version: 189.0",
    "- Rust 版本: 190.0": "- Rust version: 190.0",
    "- Rust 版本: 191.0": "- Rust version: 191.0",
    "- 稳定日期: 2025-04-03": "- Stabilization date: 2025-04-03",
    "- 稳定日期: 2025-05-15": "- Stabilization date: 2025-05-15",
    "- 稳定日期: 2025-06-26": "- Stabilization date: 2025-06-26",
    "- 稳定日期: 2025-08-07": "- Stabilization date: 2025-08-07",
    "- 稳定日期: 2025-09-18": "- Stabilization date: 2025-09-18",
    "- 稳定日期: 2025-10-30": "- Stabilization date: 2025-10-30",
    "- 稳定日期: 2025-12-11": "- Stabilization date: 2025-12-11",
    "- 稳定日期: 2026-04-16": "- Stabilization date: 2026-04-16",
    "- 文件: rust_192_features.rs": "- File: rust_192_features.rs",
    "- 文件: rust_194_features.rs": "- File: rust_194_features.rs",
    "- 文件: rust_191_features.rs": "- File: rust_191_features.rs",
    "2. 参考 `rust_192_features.rs` 了解最新特性": "2. Refer to `rust_192_features.rs` for the latest features",
    "1. 更新 Cargo.toml: `rust-version = \"1.92\"`": "1. Update Cargo.toml: `rust-version = \"1.92\"`",
    "- [历史版本: Rust 1.90.0 Release Notes](https://blog.rust-lang.org/2025/09/18/Rust-1.90.0/)": "- [Historical version: Rust 1.90.0 Release Notes](https://blog.rust-lang.org/2025/09/18/Rust-1.90.0/)",
    "- 可通过 `-C link-arg=-fuse-ld=gold` 等覆盖": "- Can be overridden with `-C link-arg=-fuse-ld=gold`, etc.",
    "// 使用 crate 内部路径": "// Use crate internal path",
    "// 此模块为归档模块，示例代码仅供参考": "// This module is archived; example code is for reference only",
    "基于编译时常量N判断数组是否为空。": "Determines if the array is empty based on compile-time constant N.",
    "若需显式指定链接器，可在 `.cargo/config.toml` 中设置：": "To explicitly specify the linker, set it in `.cargo/config.toml`:",
    "无需修改配置，工具链自动处理。": "No configuration changes needed; the toolchain handles it automatically.",
    "前提是调用者通过 `is_x86_feature_detected!` 等宏确保目标平台支持该特性。": "The caller must ensure the target platform supports this feature via `is_x86_feature_detected!` and similar macros.",
    "调用者必须确保  中的每个元素都已被正确初始化。": "The caller must ensure every element in  has been properly initialized.",
    "如果数组包含未初始化的元素，调用此函数将导致未定义行为。": "If the array contains uninitialized elements, calling this function leads to undefined behavior.",
    "确保目标平台支持 SSE2 特性，否则调用此函数是未定义行为。": "Ensure the target platform supports SSE2; otherwise, calling this function is undefined behavior.",
    "可以直接链式组合多个 let 条件和布尔条件。": "Can directly chain multiple let conditions and boolean conditions.",
    "需要使用嵌套 `if let` 或 `match`。": "Requires nested `if let` or `match`.",
    "显著减少链接时间（尤其是大型项目）。": "Significantly reduces link time (especially for large projects).",
    "允许一次性发布 workspace 中的多个 crate。": "Allows publishing multiple crates in a workspace at once.",
    "Cargo 会自动计算依赖拓扑，按正确顺序发布。": "Cargo automatically calculates the dependency topology and publishes in the correct order.",
    "提升为 **Tier 1 支持平台**，意味着：": "Promoted to **Tier 1 supported platform**, meaning:",
    "可直接使用官方 Rust 工具链，无需交叉编译": "Can use the official Rust toolchain directly without cross-compilation",
    "- 所有稳定版都提供预编译二进制": "- Precompiled binaries are provided for all stable releases",
    "- 通过完整 CI 测试": "- Full CI testing is passed",
    "- 保证与 x86_64 Windows 相同的稳定性": "- Guarantees the same stability as x86_64 Windows",
    "- `cargo build --target aarch64-pc-windows-msvc` 获得一级支持": "- `cargo build --target aarch64-pc-windows-msvc` gets Tier 1 support",
    "- Windows ARM 设备（如 Surface Pro X、Snapdragon X Elite PC）": "- Windows ARM devices (e.g., Surface Pro X, Snapdragon X Elite PC)",
    "- 减少手动发布错误": "- Reduces manual publishing errors",
    "- 确保依赖版本一致性": "- Ensures dependency version consistency",
    "- 简化 CI/CD 发布流程": "- Simplifies CI/CD release process",
    "- 只需显式指定部分 const 参数时": "- When only partially specifying const parameters",
    "- 提高代码可读性，避免写出冗余的 const 表达式": "- Improves code readability and avoids redundant const expressions",
    "- 必须使用 `unsafe`（因为编译器无法验证变参类型安全）": "- Must use `unsafe` (because the compiler cannot verify variadic type safety)",
    "- 仅在 `extern \"C\"` 函数中可用": "- Only available in `extern \"C\"` functions",
    "- 变参访问需通过 `core::ffi::VaList`（或 `std` 中的等效类型）": "- Variadic access must go through `core::ffi::VaList` (or equivalent in `std`)",
    "- 不支持 `||`（或）与 `let` 混合（因语义复杂）": "- Does not support `||` (or) mixed with `let` (due to semantic complexity)",
    "- 仅在 Edition 2024 中可用": "- Only available in Edition 2024",
    "- 解引用原始指针仍然需要 `unsafe`": "- Dereferencing raw pointers still requires `unsafe`",
    "- 只能使用 `&raw`（原始指针），不能创建 `&union.field`（引用）": "- Can only use `&raw` (raw pointer), cannot create `&union.field` (reference)",
    "- `[MaybeUninit<T>; N]` 与 `[T; N]` 保证 layout 相同": "- `[MaybeUninit<T>; N]` and `[T; N]` are guaranteed to have the same layout",
    "- `MaybeUninit<T>` 与 `T` 具有相同的内存布局和对齐方式": "- `MaybeUninit<T>` has the same memory layout and alignment as `T`",
    "- `MaybeUninit<T>` 的未初始化状态是明确定义的（不是 UB）": "- The uninitialized state of `MaybeUninit<T>` is well-defined (not UB)",
    "- 在结构体字段中使用 `MaybeUninit` 来避免不必要的初始化": "- Use `MaybeUninit` in struct fields to avoid unnecessary initialization",
    "- 从 `[MaybeUninit<T>; N]` 到 `[T; N]` 的转换": "- Conversion from `[MaybeUninit<T>; N]` to `[T; N]`",
    "- 实现 C 标准库函数（如 `printf`、`scanf`）的 Rust 包装": "- Rust wrappers for C standard library functions (e.g., `printf`, `scanf`)",
    "- 编写兼容 C 的插件接口": "- Write C-compatible plugin interfaces",
    "- 插件系统：将特定插件接口转换为通用接口": "- Plugin system: convert specific plugin interfaces to generic interfaces",
    "- 抽象层解耦：在运行时根据具体类型降级到更通用的 trait 对象": "- Abstraction layer decoupling: downgrade to more generic trait objects at runtime based on concrete types",
    "- 显式推断的常量泛型参数": "- Explicitly inferred const generic parameters",
    "- 链接速度提升：大型 workspace 链接时间可减少 20-50%": "- Link speed improvement: large workspace link time can be reduced by 20-50%",
    "- 二进制兼容性：LLD 生成的二进制与 GNU ld 基本一致": "- Binary compatibility: LLD-generated binaries are basically the same as GNU ld",
    "| 全局默认启用 | 2026 Q4–2027 Q1 | 🔴 计划 |": "| Global default enable | 2026 Q4–2027 Q1 | 🔴 Planned |",
    "| 稳定化 | 🔴 远期 | 2027+ |": "| Stabilization | 🔴 Long-term | 2027+ |",
    "| 稳定版默认 | 2027 | 🔴 远期 |": "| Stable default | 2027 | 🔴 Long-term |",
    "| Coherence 冲突 | 某些合法代码被拒绝 | 正确接受 | 🟡 检查编译错误 |": "| Coherence conflict | Some valid code is rejected | Correctly accepted | 🟡 Check compile errors |",
    "| Coherence 迁移 | 2026 Q2 | 🟡 推进中 |": "| Coherence migration | 2026 Q2 | 🟡 In progress |",
    "| 原型实现 | 🔴 无 | — |": "| Prototype implementation | 🔴 None | — |",
    "| 设计讨论 | 🟡 活跃 | — |": "| Design discussion | 🟡 Active | — |",
    "✅ 推荐：使用 try_into 进行安全转换": "✅ Recommended: Use try_into for safe conversion",
    "❌ 非 Object-Safe 示例 (使用了 Self: Sized)": "❌ Non-Object-Safe example (uses Self: Sized)",
    "✅ 混合策略: 将 Sized 方法移到独立的 super trait": "✅ Hybrid strategy: Move Sized methods to a separate super trait",
    "⚠️ 边界情况：f64 到整数的精度丢失边界": "⚠️ Edge case: Precision loss boundary for f64 to integer",
    "⚠️ `LazyLock::from(value)` **不是 `const`**，因此不能用于 `static`。": "⚠️ `LazyLock::from(value)` **is not `const`**, so it cannot be used in `static`.",
    "⚠️ **注意**: 本示例针对 Rust 1.89 版本编写，部分特性在 Rust 1.90 中已有更新。": "⚠️ **Note**: This example is written for Rust 1.89; some features have been updated in Rust 1.90.",
    "> **状态**: 🟡 跟踪观察": "> **Status**: 🟡 Tracking",
    "`foo::<_, N>(...)` — `_` 表示\"让编译器推断这个 const 参数\"": "`foo::<_, N>(...)` — `_` means \"let the compiler infer this const parameter\"",
    "`&raw mut union.field` 直接产生原始指针（不创建引用），": "`&raw mut union.field` directly produces a raw pointer (does not create a reference),",
    "因此不涉及 Rust 的引用规则，可以在 safe 代码中使用。": "Therefore, it does not involve Rust's reference rules and can be used in safe code.",
    "联合体（union）字段的引用创建之前需要 `unsafe`，": "Creating references to union fields previously required `unsafe`,",
    "因为编译器无法确定哪个变体是活跃的。": "because the compiler cannot determine which variant is active.",
    "安全地转换已初始化的 MaybeUninit 数组": "Safely converts an initialized MaybeUninit array",
    "安全函数 + ``#[target_feature]`` 组合允许，但调用点必须在 `unsafe` 块中。": "Safe functions + ``#[target_feature]`` combination is allowed, but the call site must be in an `unsafe` block.",
    "Rust 1.86.0 允许在安全函数上使用 ``#[target_feature]``，": "Rust 1.86.0 allows ``#[target_feature]`` on safe functions,",
    "前提是调用者通过 `is_x86_feature_detected!` 等宏确保目标平台支持该特性。": "provided the caller ensures the target platform supports the feature via `is_x86_feature_detected!` and similar macros.",
    "Rust 1.91.0 稳定了 C 风格变参函数的声明，允许 Rust 函数接受可变数量的参数，": "Rust 1.91.0 stabilized C-style variadic function declarations, allowing Rust functions to accept a variable number of arguments,",
    "Rust 1.92.0 正式文档化了 `MaybeUninit` 的内存表示保证：": "Rust 1.92.0 formally documented `MaybeUninit`'s memory representation guarantees:",
    "Rust 1.92.0 允许在 safe 代码中使用 `&raw const` 和 `&raw mut`": "Rust 1.92.0 allows `&raw const` and `&raw mut` in safe code",
    "Rust 1.90.0 稳定了 `cargo publish` 的多包发布支持，": "Rust 1.90.0 stabilized multi-package publishing support for `cargo publish`,",
    "Rust 1.90.0 在 `x86_64-unknown-linux-gnu` 目标上默认使用 LLD 链接器，": "Rust 1.90.0 uses LLD linker by default on the `x86_64-unknown-linux-gnu` target,",
    "Rust 1.89.0 允许在 turbofish 语法中显式使用 `_` 来让编译器推断 const 泛型参数。": "Rust 1.89.0 allows explicitly using `_` in turbofish syntax to let the compiler infer const generic parameters.",
    "Rust 1.88.0 在 2024 Edition 中稳定了 let chains，": "Rust 1.88.0 stabilized let chains in the 2024 Edition,",
    "Rust 1.86.0 稳定了 trait 对象的向上转换（upcasting）：": "Rust 1.86.0 stabilized trait object upcasting:",
    "允许在 `if` 和 `while` 条件中将 `let` 模式与布尔表达式混合使用。": "Allows mixing `let` patterns with boolean expressions in `if` and `while` conditions.",
    "允许一次性发布 workspace 中的多个 crate。": "Allows publishing multiple crates in a workspace at once.",
    "显著减少链接时间（尤其是大型项目）。": "Significantly reduces link time (especially for large projects).",
    "可以将 `dyn SubTrait` 转换为 `dyn SuperTrait`。": "Can convert `dyn SubTrait` to `dyn SuperTrait`.",
    "本模块展示了 Rust 186.0 (2025-04-03) 的关键语言特性和工具链改进。": "This module showcases key language features and toolchain improvements of Rust 186.0 (2025-04-03).",
    "本模块展示了 Rust 187.0 (2025-05-15) 的关键语言特性和工具链改进。": "This module showcases key language features and toolchain improvements of Rust 187.0 (2025-05-15).",
    "本模块展示了 Rust 188.0 (2025-06-26) 的关键语言特性和工具链改进。": "This module showcases key language features and toolchain improvements of Rust 188.0 (2025-06-26).",
    "本模块展示了 Rust 189.0 (2025-08-07) 的关键语言特性和工具链改进。": "This module showcases key language features and toolchain improvements of Rust 189.0 (2025-08-07).",
    "本模块展示了 Rust 190.0 (2025-09-18) 的关键语言特性和工具链改进。": "This module showcases key language features and toolchain improvements of Rust 190.0 (2025-09-18).",
    "本模块展示了 Rust 191.0 (2025-10-30) 的关键语言特性和工具链改进。": "This module showcases key language features and toolchain improvements of Rust 191.0 (2025-10-30).",
    "本模块展示了 Rust 192.0 (2025-12-11) 的关键语言特性和工具链改进。": "This module showcases key language features and toolchain improvements of Rust 192.0 (2025-12-11).",
    "当前活跃版本为 Rust 1.94，请使用最新模块获取最新特性。": "The current active version is Rust 1.94; please use the latest module for the newest features.",
    "**注意**：截至 Rust 1.95.0 stable，`c_variadic` 特性尚未完全稳定。": "**Note**: As of Rust 1.95.0 stable, the `c_variadic` feature is not fully stabilized.",
    "已经广泛存在。1.92 只是将这些已有保证正式写入文档。": "Already widely existed. 1.92 just formally documented these existing guarantees.",
    "之前版本中，`transmute_copy` 和 `ptr::read` 在 `MaybeUninit` 上的使用": "In previous versions, the use of `transmute_copy` and `ptr::read` on `MaybeUninit`",
    "利用 1.92 文档化的 layout 保证。": "Utilizes the 1.92 documented layout guarantees.",
    "这使得以下模式成为官方认可的 safe/unsafe 边界：": "This makes the following patterns officially recognized safe/unsafe boundaries:",
    "在 safe 代码中获取联合体字段的原始指针": "Gets raw pointers to union fields in safe code",
    "| 平台 | Tier | 预编译二进制 | 测试覆盖 |": "| Platform | Tier | Precompiled Binary | Test Coverage |",
    "**来源**: [Rust Project Goals 2026 — Next-generation trait solver](https://rust-lang.github.io/rust-project-goals/2026/flagships.html)": "**Source**: [Rust Project Goals 2026 — Next-generation trait solver](https://rust-lang.github.io/rust-project-goals/2026/flagships.html)",
    "**来源**: [Rust Project Goals 2026 — Const Generics](https://rust-lang.github.io/rust-project-goals/2026/flagships.html)": "**Source**: [Rust Project Goals 2026 — Const Generics](https://rust-lang.github.io/rust-project-goals/2026/flagships.html)",
    "· [rustc-next-trait-solver 源码](https://github.com/rust-lang/rust/tree/master/compiler/rustc_next_trait_solver)": "· [rustc-next-trait-solver source](https://github.com/rust-lang/rust/tree/master/compiler/rustc_next_trait_solver)",
    "参考: [Rust 1.90.0 Release Notes](https://blog.rust-lang.org/2025/09/18/Rust-1.90.0/)": "Reference: [Rust 1.90.0 Release Notes](https://blog.rust-lang.org/2025/09/18/Rust-1.90.0/)",
    "- `trait_upcasting`: Trait 对象向上转换（dyn Trait + Trait -> dyn Trait）": "- `trait_upcasting`: Trait object upcasting (dyn Trait + Trait -> dyn Trait)",
    "- `lld_default`: x86_64 默认 LLD 链接器": "- `lld_default`: x86_64 default LLD linker",
    "- `explicit_inferred_const`: 显式推断 const 参数": "- `explicit_inferred_const`: Explicitly inferred const parameters",
    "- `aarch64_windows_tier1`: `aarch64-pc-windows-msvc` 晋升 Tier 1": "- `aarch64_windows_tier1`: `aarch64-pc-windows-msvc` promoted to Tier 1",
    "- `cargo_multi_publish`: Cargo 多包发布稳定": "- `cargo_multi_publish`: Cargo multi-package publishing stabilized",
    "- `let_chains`: Let Chains 在 2024 Edition 中稳定": "- `let_chains`: Let Chains stabilized in 2024 Edition",
    "- `raw_ref_union`: `&raw [mut|const]` 对联合体字段在 safe 代码中允许": "- `raw_ref_union`: `&raw [mut|const]` allowed on union fields in safe code",
    "- `target_feature_safe`: 安全函数上的 `#[target_feature]`": "- `target_feature_safe`: `#[target_feature]` on safe functions",
    "- `c_variadic`: C 风格变参函数声明稳定": "- `c_variadic`: C-style variadic function declarations stabilized",
    "- **标准库**: NonZero::div_ceil、rotate_right 等": "- **Standard library**: NonZero::div_ceil, rotate_right, etc.",
    "- **标准库**: NonZero::div_ceil、rotate_right、Location::file_as_c_str": "- **Standard library**: NonZero::div_ceil, rotate_right, Location::file_as_c_str",
    "- **语言特性**: MaybeUninit 文档化、联合体原始引用、关联项多边界等": "- **Language features**: MaybeUninit documentation, union raw references, multiple associated item bounds, etc.",
    "- **性能优化**: 迭代器方法特化、改进的编译优化": "- **Performance optimizations**: Iterator method specialization, improved compilation optimizations",
    "- `data`: 第一个生命周期受限的数据": "- `data`: First lifetime-restricted data",
    "- `data`: 长度为N的数组数据": "- `data`: Array data of length N",
    "- `&'a self`: 生命周期受限的self引用": "- `&'a self`: Lifetime-restricted self reference",
    "* `'a` - 引用的生命周期": "* `'a` - Lifetime of the reference",
    "1.86 之前，``#[target_feature]`` 只能用于 `unsafe fn`，": "Before 1.86, ``#[target_feature]`` could only be used on `unsafe fn`,",
}

VERB_MAP = {
    "获取": "Gets", "设置": "Sets", "返回": "Returns", "检查": "Checks",
    "创建": "Creates", "初始化": "Initializes", "演示": "Demonstrates",
    "删除": "Deletes", "插入": "Inserts", "尝试": "Attempts to",
    "计算": "Computes", "更新": "Updates", "发送": "Sends", "接收": "Receives",
    "处理": "Processes", "验证": "Validates", "比较": "Compares", "转换": "Converts",
    "查找": "Finds", "遍历": "Iterates over", "打印": "Prints", "显示": "Displays",
    "生成": "Generates", "解析": "Parses", "绑定": "Binds", "复制": "Copies",
    "克隆": "Clones", "交换": "Swaps", "合并": "Merges", "分割": "Splits",
    "连接": "Joins", "排序": "Sorts", "过滤": "Filters", "映射": "Maps",
    "归约": "Reduces", "收集": "Collects", "累加": "Accumulates", "清空": "Clears",
    "重置": "Resets", "启动": "Starts", "停止": "Stops", "暂停": "Pauses",
    "恢复": "Resumes", "等待": "Waits for", "唤醒": "Wakes up", "通知": "Notifies",
    "锁定": "Locks", "解锁": "Unlocks", "读取": "Reads", "写入": "Writes",
    "分配": "Allocates", "释放": "Releases", "移动": "Moves", "推送": "Pushes",
    "弹出": "Pops", "压入": "Pushes", "查看": "Views", "访问": "Accesses",
    "修改": "Modifies", "增加": "Increases", "减少": "Decreases", "自增": "Increments",
    "自减": "Decrements", "乘以": "Multiplies by", "除以": "Divides by",
    "取模": "Modulos", "取整": "Rounds", "向上取整": "Ceils", "向下取整": "Floors",
    "四舍五入": "Rounds", "绝对值": "Absolute value of", "最大值": "Maximum of",
    "最小值": "Minimum of", "求和": "Sum of", "平均值": "Average of",
    "中位数": "Median of", "哈希": "Hashes", "编码": "Encodes", "解码": "Decodes",
    "序列化": "Serializes", "反序列化": "Deserializes", "压缩": "Compresses",
    "解压": "Decompresses", "加密": "Encrypts", "解密": "Decrypts", "签名": "Signs",
    "验证签名": "Verifies signature of", "摘要": "Digests", "随机": "Randomizes",
    "洗牌": "Shuffles", "采样": "Samples", "抽样": "Samples", "测试": "Tests",
    "基准测试": "Benchmarks", "性能测试": "Performance tests", "压力测试": "Stress tests",
    "模糊测试": "Fuzz tests", "单元测试": "Unit tests", "集成测试": "Integration tests",
    "端到端测试": "End-to-end tests", "文档测试": "Doc tests",
}

WORD_MAP = {
    "的": "", "和": "and", "与": "and", "或": "or", "在": "in", "中": "in",
    "上": "on", "下": "under", "前": "before", "后": "after", "内": "inside",
    "外": "outside", "之间": "between", "为": "as", "被": "by", "从": "from",
    "到": "to", "向": "to", "对": "to", "对于": "for", "关于": "about",
    "通过": "through", "使用": "use", "利用": "use", "采用": "use", "基于": "based on",
    "根据": "according to", "按照": "according to", "由于": "due to",
    "因为": "because", "所以": "therefore", "因此": "therefore", "如果": "if",
    "那么": "then", "否则": "otherwise", "当": "when", "一旦": "once", "直到": "until",
    "除非": "unless", "虽然": "although", "但是": "but", "然而": "however",
    "不过": "however", "而且": "and", "并且": "and", "或者": "or", "以及": "and",
    "等": "etc.", "等等": "etc.", "例如": "for example", "比如": "for example",
    "像": "like", "如同": "like", "类似": "similar to", "相同": "same",
    "不同": "different", "差异": "difference", "区别": "difference", "变化": "change",
    "改变": "change", "调整": "adjust", "优化": "optimize", "改进": "improve",
    "增强": "enhance", "提升": "improve", "扩大": "expand", "缩小": "shrink",
    "延长": "extend", "缩短": "shorten", "加速": "accelerate", "减速": "decelerate",
    "提高": "improve", "降低": "reduce", "升高": "raise", "下降": "drop",
    "上升": "rise", "下跌": "fall", "稳定": "stable", "不稳定": "unstable",
    "动态": "dynamic", "静态": "static", "全局": "global", "局部": "local",
    "内部": "internal", "外部": "external", "公共": "public", "私有": "private",
    "开放": "open", "封闭": "closed", "安全": "safe", "不安全": "unsafe",
    "危险": "dangerous", "可靠": "reliable", "不可靠": "unreliable", "正确": "correct",
    "错误": "error", "准确": "accurate", "精确": "precise", "大致": "approximate",
    "大约": "approximately", "大概": "probably", "可能": "possible", "不可能": "impossible",
    "可以": "can", "能够": "can", "不能": "cannot", "必须": "must", "必需": "required",
    "需要": "need", "不需要": "not needed", "应该": "should", "应当": "should",
    "不应": "should not", "允许": "allow", "禁止": "prohibit", "支持": "support",
    "不支持": "not supported", "兼容": "compatible", "不兼容": "incompatible",
    "适用": "applicable", "不适用": "not applicable", "有效": "valid", "无效": "invalid",
    "合法": "legal", "非法": "illegal", "正常": "normal", "异常": "abnormal",
    "标准": "standard", "非标准": "non-standard", "通用": "general", "特定": "specific",
    "特殊": "special", "一般": "general", "普通": "ordinary", "常见": "common",
    "罕见": "rare", "唯一": "unique", "单一": "single", "多个": "multiple",
    "所有": "all", "部分": "part", "全部": "all", "整体": "whole", "完整": "complete",
    "不完整": "incomplete", "完美": "perfect", "理想": "ideal", "现实": "reality",
    "实际": "actual", "真实": "real", "虚假": "false", "模拟": "simulate",
    "仿真": "simulate", "虚拟": "virtual", "物理": "physical", "逻辑": "logical",
    "抽象": "abstract", "具体": "concrete", "简单": "simple", "复杂": "complex",
    "容易": "easy", "困难": "difficult", "方便": "convenient", "麻烦": "troublesome",
    "快速": "fast", "慢速": "slow", "高速": "high-speed", "低速": "low-speed",
    "高效": "efficient", "低效": "inefficient", "高性能": "high-performance",
    "低性能": "low-performance", "最佳": "best", "最差": "worst", "更好": "better",
    "更差": "worse", "最大": "maximum", "最小": "minimum", "最多": "at most",
    "最少": "at least", "最高": "highest", "最低": "lowest", "最长": "longest",
    "最短": "shortest", "最早": "earliest", "最晚": "latest", "最新": "latest",
    "最旧": "oldest", "最前": "first", "最后": "last", "初始": "initial",
    "最终": "final", "开始": "start", "结束": "end", "起点": "starting point",
    "终点": "ending point", "源头": "source", "目标": "target", "目的": "purpose",
    "意图": "intention", "原因": "reason", "结果": "result", "后果": "consequence",
    "效果": "effect", "影响": "impact", "作用": "role", "功能": "function",
    "用途": "use", "用法": "usage", "示例": "example", "实例": "instance",
    "案例": "case", "情况": "situation", "状态": "state", "条件": "condition",
    "环境": "environment", "上下文": "context", "背景": "background",
    "前景": "foreground", "场景": "scenario", "配置": "configuration",
    "设置": "settings", "选项": "options", "参数": "parameters", "变量": "variables",
    "常量": "constants", "字段": "fields", "属性": "properties", "特性": "features",
    "特征": "traits", "特点": "characteristics", "性质": "nature", "类型": "type",
    "类别": "category", "种类": "kind", "等级": "level", "层次": "level",
    "级别": "level", "阶段": "stage", "步骤": "step", "过程": "process",
    "流程": "flow", "程序": "program", "代码": "code", "源码": "source code",
    "脚本": "script", "模块": "module", "组件": "component", "部件": "part",
    "元素": "element", "单元": "unit", "个体": "individual", "对象": "object",
    "实体": "entity", "主体": "subject", "客体": "object", "集合": "collection",
    "组": "group", "群": "group", "队": "team", "列": "column", "行": "row",
    "表": "table", "图": "graph", "树": "tree", "森林": "forest", "网": "network",
    "网格": "grid", "链": "chain", "列表": "list", "队列": "queue", "栈": "stack",
    "堆": "heap", "映射": "map", "字典": "dictionary", "数组": "array",
    "向量": "vector", "矩阵": "matrix", "张量": "tensor", "标量": "scalar",
    "指针": "pointer", "引用": "reference", "句柄": "handle", "标识符": "identifier",
    "名称": "name", "命名": "naming", "命名空间": "namespace", "作用域": "scope",
    "域": "domain", "范围": "range", "区间": "interval", "区域": "region",
    "空间": "space", "内存": "memory", "存储": "storage", "缓存": "cache",
    "缓冲": "buffer", "缓冲区": "buffer", "数据": "data", "信息": "information",
    "消息": "message", "信号": "signal", "事件": "event", "通知": "notification",
    "警告": "warning", "异常": "exception", "故障": "fault", "缺陷": "defect",
    "漏洞": "vulnerability", "风险": "risk", "问题": "problem", "疑问": "question",
    "答案": "answer", "解决方案": "solution", "方法": "method", "方式": "way",
    "手段": "means", "途径": "approach", "策略": "strategy", "战术": "tactic",
    "计划": "plan", "方案": "plan", "项目": "project", "工程": "project",
    "任务": "task", "作业": "job", "工作": "work", "操作": "operation",
    "行为": "behavior", "动作": "action", "活动": "activity", "事务": "transaction",
    "业务": "business", "服务": "service", "接口": "interface", "协议": "protocol",
    "规范": "specification", "约定": "convention", "规则": "rule", "定律": "law",
    "定理": "theorem", "原理": "principle", "理论": "theory", "概念": "concept",
    "定义": "definition", "说明": "description", "描述": "description",
    "解释": "explanation", "注释": "comment", "文档": "documentation",
    "记录": "record", "日志": "log", "跟踪": "trace", "调试": "debug",
    "验证": "verification", "确认": "confirmation", "检查": "check",
    "审查": "review", "审计": "audit", "分析": "analysis", "评估": "evaluation",
    "评价": "evaluation", "测量": "measurement", "度量": "metric", "指标": "indicator",
    "指数": "index", "系数": "coefficient", "比率": "ratio", "比例": "proportion",
    "百分比": "percentage", "频率": "frequency", "周期": "period", "速率": "rate",
    "速度": "speed", "时间": "time", "时刻": "moment", "时段": "time period",
    "持续时间": "duration", "延迟": "delay", "等待": "wait", "超时": "timeout",
    "间隔": "interval", "间隙": "gap", "空白": "blank", "空格": "space",
    "空": "empty", "非空": "non-empty", "零": "zero", "一": "one", "二": "two",
    "三": "three", "多": "multiple", "单": "single", "双": "double", "半": "half",
    "全": "full", "片段": "fragment", "段": "segment", "节": "section",
    "章": "chapter", "篇": "article", "页": "page", "字符": "character",
    "字符串": "string", "文本": "text", "字节": "byte", "位": "bit", "比特": "bit",
    "字": "word", "双字": "double word", "四字": "quad word", "整数": "integer",
    "浮点数": "floating point", "小数": "decimal", "分数": "fraction",
    "正数": "positive number", "负数": "negative number", "偶数": "even number",
    "奇数": "odd number", "素数": "prime number", "合数": "composite number",
    "因子": "factor", "倍数": "multiple", "最大公约数": "GCD", "最小公倍数": "LCM",
    "取模": "modulo", "取余": "remainder", "整除": "integer division",
    "除法": "division", "乘法": "multiplication", "加法": "addition",
    "减法": "subtraction", "幂": "power", "指数": "exponent", "对数": "logarithm",
    "根": "root", "平方": "square", "立方": "cube", "平方根": "square root",
    "立方根": "cube root", "阶乘": "factorial", "排列": "permutation",
    "组合": "combination", "概率": "probability", "统计": "statistics",
    "伪随机": "pseudo-random", "确定性": "deterministic", "非确定性": "non-deterministic",
    "同步": "synchronous", "异步": "asynchronous", "并发": "concurrent",
    "并行": "parallel", "串行": "serial", "顺序": "sequential", "逆序": "reverse",
    "随机顺序": "random order", "排序": "sort", "有序": "ordered", "无序": "unordered",
    "升序": "ascending", "降序": "descending", "字典序": "lexicographical order",
    "拓扑序": "topological order", "前序": "pre-order", "中序": "in-order",
    "后序": "post-order", "层序": "level-order",
}

CHINESE_RE = re.compile(r'[\u4e00-\u9fff]')


def translate_line(text):
    if not text or not CHINESE_RE.search(text):
        return None
    if text in EXACT:
        return EXACT[text]
    for v, e in sorted(VERB_MAP.items(), key=lambda x: -len(x[0])):
        if text.startswith(v):
            return e + text[len(v):]
    result = text
    for cn, en in sorted(WORD_MAP.items(), key=lambda x: -len(x[0])):
        result = result.replace(cn, en)
    result = re.sub(r'\s+', ' ', result).strip()
    if CHINESE_RE.search(result):
        return None
    if not result or result in [',', '.', ';', ':', '!', '?', '-', '*', '|']:
        return None
    return result


def process_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    modified = False
    new_lines = []
    for i, line in enumerate(lines):
        new_lines.append(line)
        m = re.match(r'^(\s*(///|//!))(\s*)(.*)$', line)
        if not m:
            continue
        prefix = m.group(1)
        spaces = m.group(3)
        content = m.group(4).rstrip('\n')
        if not CHINESE_RE.search(content):
            continue
        # Check if next line is already an English doc comment
        if i + 1 < len(lines):
            next_m = re.match(r'^(\s*(///|//!))(\s*)(.*)$', lines[i + 1])
            if next_m:
                next_content = next_m.group(4).rstrip('\n')
                if next_content and not CHINESE_RE.search(next_content):
                    continue
        translation = translate_line(content)
        if translation:
            # Check if next line is already this translation or starts with it
            if i + 1 < len(lines):
                next_m = re.match(r'^(\s*(///|//!))(\s*)(.*)$', lines[i + 1])
                if next_m:
                    next_content = next_m.group(4).rstrip('\n')
                    if next_content:
                        first_word = translation.split()[0] if translation.split() else translation
                        if next_content == translation or next_content.startswith(first_word):
                            continue
            new_lines.append(f"{prefix}{spaces}{translation}\n")
            modified = True
    if modified:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.writelines(new_lines)
        return True
    return False


def main():
    crates = [
        'crates/c02_type_system/src',
        'crates/c03_control_fn/src',
        'crates/c04_generic/src',
        'crates/c05_threads/src',
    ]
    modified_files = []
    for crate in crates:
        for root, dirs, files in os.walk(crate):
            for file in sorted(files):
                if file.endswith('.rs'):
                    filepath = os.path.join(root, file)
                    if process_file(filepath):
                        modified_files.append(filepath)
    print(f"Modified {len(modified_files)} files:")
    for f in modified_files:
        print(f"  {f}")
    with open('modified_files.txt', 'w', encoding='utf-8') as f:
        for filepath in modified_files:
            f.write(filepath + '\n')


if __name__ == '__main__':
    main()
