apiVersion: v1
kind: Pod
metadata:
  name: c13-demo
  labels:
    app: c13-demo
spec:
  containers:
    - name: nginx
      image: docker.io/library/nginx:latest
      args: []
      env: []
      resources:
        limits:
          cpu: "500m"
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "64Mi"
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 10

