[package]
name = "c05_threads"
version = "0.1.0"
edition = "2024"
resolver = "3"

[dependencies]
crossbeam = ">=0.8.1"
rayon = ">=1.10"


[lib]
name = "c05_threads"
path = "src/lib.rs"

[[bin]]
name = "c05_threads"
path = "src/bin/main.rs"
