[build]
# 启用并行编译
jobs = 0
# 启用增量编译
incremental = true

[profile.dev]
# 开发模式优化级别
opt-level = 0
# 启用调试信息
debug = true
# 启用溢出检查
overflow-checks = true

[profile.release]
# 发布模式优化级别
opt-level = 3
# 启用链接时优化
lto = true
# 减少代码生成单元以提高优化
codegen-units = 1
# 启用panic优化
panic = "abort"
# 启用strip以减少二进制大小
strip = true

[profile.bench]
# 基准测试模式优化级别
opt-level = 3
# 启用链接时优化
lto = true
# 减少代码生成单元
codegen-units = 1

[profile.test]
# 测试模式优化级别
opt-level = 0
# 启用调试信息
debug = true
# 启用溢出检查
overflow-checks = true

[target.'cfg(target_arch = "x86_64")']
# x86_64特定优化
rustflags = [
    "-C", "target-cpu=native",
    "-C", "target-feature=+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+avx,+avx2",
    "-C", "link-arg=-Wl,-O1",
]

[target.'cfg(target_arch = "aarch64")']
# ARM64特定优化
rustflags = [
    "-C", "target-cpu=native",
    "-C", "target-feature=+fp,+simd",
]

[net]
# 网络配置
git-fetch-with-cli = true

[registries.crates-io]
# crates.io配置
index = "https://github.com/rust-lang/crates.io-index"

[registries.crates-io-alt]
# 备用crates.io镜像
index = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"

[alias]
# 常用命令别名
b = "build"
c = "check"
t = "test"
r = "run"
f = "fmt"
cl = "clippy"
doc = "doc --open"
bench = "bench --all-features"
test-all = "test --all-features --all-targets"
check-all = "check --all-features --all-targets"
