[package]
name = "c11_frameworks"
version = "0.1.0"
edition = "2024"
resolver = "3"

[dependencies]
thiserror = { version = ">=2.0.12", features = ["full"] }
tokio = { version = ">=1.44.1", features = ["full"] }
anyhow = "1.0.97"

diesel = { version = "2.2.8", features = ["postgres"] }
dotenvy = "0.15"
diesel_migrations = { version = "2.0", features = ["sqlite", "mysql", "postgres"] }

serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[lib]
name = "c11_frameworks"
path = "src/lib.rs"

[[bin]]
name = "c11_frameworks"
path = "src/bin/main.rs"
