[package]
name = "rust-doc-search"
version = "1.0.0"
edition = "2024"
authors = ["Rust Learning Community"]
description = "智能文档搜索工具 - Rust 学习项目"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"
walkdir = "2.5"

[dev-dependencies]

