[package]
name = "c16_webassembly"
version = "0.1.0"
edition = "2024"
resolver = "3"
rust-version = "1.90"
authors = ["Rust WebAssembly Team"]
description = "WebAssembly 2.0 与 Rust 1.90 集成演示项目 - 包含2025年9月最新开源库、工具链和应用案例"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/webassembly"
keywords = ["webassembly", "wasm", "rust", "vm", "runtime"]
categories = ["web-programming", "wasm"]

# WebAssembly CPU指令集优化配置在根Cargo.toml中统一管理

[dependencies]
# 序列化和反序列化
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true }
serde_bytes = "0.11.19"

# 错误处理
thiserror = { workspace = true }
anyhow = { workspace = true }

# 异步运行时
tokio = { workspace = true, features = ["full"] }

# 工具库
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
log = { workspace = true }
env_logger = "0.11.8"

# WebAssembly 相关 - 2025年最新版本 (支持WebAssembly 2.0)
wasm-bindgen = "0.2.103"  # 最新稳定版本
wasm-bindgen-futures = "0.4.53"
js-sys = "0.3.80"
web-sys = "0.3.80"
wasmtime = "37.0.0"  # 最新版本，支持WebAssembly 2.0
wasmparser = "0.239.0"  # 升级到最新版本
wasm-encoder = "0.239.0"  # 升级到最新版本

# 数学和算法
num-traits = "0.2.19"
num-bigint = "0.4.6"
num-complex = "0.4.6"

# 内存管理
bumpalo = "3.19.0"

# 性能分析
criterion = { version = "0.5.1", optional = true }

# 测试工具
proptest = { version = "1.8.0", optional = true }

[dev-dependencies]
criterion = "0.5.1"
proptest = "1.8.0"
tempfile = "3.22.0"

[features]
default = ["std"]
std = []
no_std = []
bench = ["criterion"]
test = ["proptest"]

[[bench]]
name = "performance_benchmarks"
harness = false
required-features = ["bench"]

[[example]]
name = "rust_190_demo"
path = "examples/rust_190_demo.rs"

[[example]]
name = "webassembly_2_0_demo"
path = "examples/webassembly_2_0_demo.rs"

[[example]]
name = "image_processing_demo"
path = "examples/image_processing_demo.rs"

[[example]]
name = "scientific_computing_demo"
path = "examples/scientific_computing_demo.rs"

