[package]
name = "c19_ai"
version = "0.3.0"
edition = "2024"
resolver = "3"
description = "AI and Machine Learning with Rust 1.89 - 人工智能与机器学习 (2025 Edition)"
authors = ["Rust AI Team"]
license = "MIT"
repository = "https://github.com/rust-lang/c19_ai"
keywords = ["ai", "machine-learning", "deep-learning", "neural-networks", "nlp", "computer-vision", "llm", "transformers", "rust-189", "candle", "burn", "tch", "dfdx"]
categories = ["science", "machine-learning", "algorithms"]
rust-version = "1.90"

# AI/ML CPU指令集优化配置在根Cargo.toml中统一管理

[dependencies]
# 核心依赖 - 使用工作区统一版本
serde = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }

# 数学和数值计算 - 2025年最新版本
ndarray = { version = "0.16.0", features = ["serde", "rayon", "approx"] }
nalgebra = "0.34.0"
num-traits = "0.2.18"
num-complex = "0.4.0"
approx = "0.5.0"
statrs = "0.18.0"

# 机器学习核心库 - 2025年最新版本
linfa = { version = "0.7.0", optional = true }
smartcore = { version = "0.4.0", optional = true }
candle-core = { workspace = true, optional = true }
candle-nn = { workspace = true, optional = true }
candle-transformers = { workspace = true, optional = true }
candle-datasets = { version = "0.9.1", optional = true }
candle-kernels = { version = "0.9.1", optional = true }

# 深度学习框架 - 2025年最新版本
# burn = { version = "0.13", optional = true }  # 暂时禁用以避免工作区冲突
tch = { workspace = true, optional = true }
dfdx = { version = "0.13.0", optional = true }

# 自然语言处理 - 2025年最新版本
tokenizers = { version = "0.22.0", optional = true }
rust-bert = { version = "0.23.0", optional = true }
llm-chain = { version = "0.13.0", optional = true }
llm-chain-openai = { version = "0.13.0", optional = true }
llm-chain-llama = { version = "0.13.0", optional = true }
llm-chain-local = { version = "0.12.0", optional = true }

# 2025年最新深度学习框架 - Burn
# burn = { workspace = true, optional = true }  # 暂时禁用，存在版本兼容性问题
# burn-ndarray = { workspace = true, optional = true }  # 暂时禁用，存在版本兼容性问题
# burn-tch 暂时禁用，与现有tch版本冲突

# 计算机视觉 - 2025年最新版本
opencv = { version = "0.95.0", optional = true }
image = { version = "0.25.8", optional = true }
imageproc = { version = "0.25.0", optional = true }

# 数据处理 - 2025年最新版本
polars = { version = "0.50.0", features = ["lazy", "temporal", "strings", "dtype-categorical", "dtype-struct"], optional = true }
datafusion = { version = "49.0.0", optional = true }
arrow = { version = "56.0.0", optional = true }

# 向量数据库和搜索 - 2025年最新版本
qdrant-client = { version = "1.8.0", optional = true }
tantivy = { version = "0.25.0", optional = true }
hnsw_rs = { version = "0.3.0", optional = true }

# 网络和API - 使用工作区统一版本
reqwest = { workspace = true }
async-openai = { version = "0.29.0", optional = true }
openai = { version = "1.0.0", optional = true }

# 序列化和配置 - 2025年最新版本
toml = { workspace = true }
serde_yaml = { workspace = true }
bincode = { workspace = true }
ron = "0.11.0"
serde_json = { workspace = true }

# 日志和监控 - 使用工作区统一版本
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
metrics = { workspace = true, optional = true }
metrics-exporter-prometheus = { workspace = true, optional = true }

# 并发和性能 - 统一使用工作区版本
rayon = { workspace = true }
crossbeam = { workspace = true }
dashmap = { workspace = true }
parking_lot = { workspace = true }
tokio-util = { workspace = true }

# 测试和基准测试 - 使用工作区/可用最新
criterion = { workspace = true, features = ["html_reports"] }
proptest = { workspace = true }
tempfile = { workspace = true }

# AI 特定依赖 - 2025年最新版本
# 大语言模型支持
llama-cpp-2 = { version = "0.1.0", optional = true }
# 图神经网络
petgraph = { workspace = true, optional = true }
# 时间序列 - 使用工作区统一版本
chrono = { workspace = true, optional = true }
# 配置管理 - 使用可用版本
config = { workspace = true }
# 错误处理增强
miette = "7.0.0"
# 内存管理
bumpalo = "3.19.0"
# 异步运行时增强 - 使用工作区版本
futures = { workspace = true }
async-trait = { workspace = true }

# 新增：2025年最新AI特性
# 强化学习 (暂时禁用，存在pyo3安全漏洞)
# gymnasium-rs = { version = "0.1.0", optional = true }

[dev-dependencies]
tempfile = { workspace = true }
proptest = { workspace = true }
tokio-test = { workspace = true }

[features]
# 将默认特性限制为纯 CPU 传统 ML，避免 workspace 级别的冲突
default = ["basic-ai"]
# 基础 AI 功能
basic-ai = ["dep:linfa", "dep:smartcore"]
# 深度学习框架（均为可选且非默认启用）
candle = ["dep:candle-core", "dep:candle-nn", "dep:candle-transformers", "dep:candle-datasets"]
# burn = ["dep:burn"]  # 暂时禁用以避免工作区冲突
tch = ["dep:tch"]
dfdx = ["dep:dfdx"]
# GPU 支持
gpu = ["candle", "tch"]
# Metal 支持 (macOS GPU)
metal = []
# CUDA 支持 (NVIDIA GPU)
cuda = []
# 大语言模型
llm = ["dep:llm-chain", "dep:llm-chain-openai", "dep:llm-chain-llama", "dep:llm-chain-local", "dep:llama-cpp-2"]
# OpenAI 集成
openai = ["dep:async-openai", "dep:openai", "dep:llm-chain-openai"]
# 计算机视觉
vision = ["dep:opencv", "dep:image", "dep:imageproc"]
# 自然语言处理
nlp = ["dep:rust-bert", "dep:tokenizers", "dep:llm-chain"]
# 数据处理
data = ["dep:polars", "dep:datafusion", "dep:arrow"]
# 向量搜索
search = ["dep:qdrant-client", "dep:tantivy", "dep:hnsw_rs"]
# 模型管理与管道控制
management = []
# 强化学习 (暂时禁用，存在pyo3安全漏洞)
# reinforcement = ["dep:gymnasium-rs"]
# 图神经网络
gnn = ["dep:petgraph"]
# 时间序列
timeseries = ["dep:chrono"]
# 监控和指标
monitoring = ["dep:metrics", "dep:metrics-exporter-prometheus"]
# 多模态AI
multimodal = []
# 联邦学习
federated = []
# 边缘AI
edge = []
# 量子机器学习
quantum = []
# 2025年最新深度学习框架
# burn = ["dep:burn", "dep:burn-ndarray"]  # 暂时禁用，存在版本兼容性问题

# 完整功能（注意：这会拉入多种后端及其系统依赖）
full = ["candle", "dfdx", "llm", "vision", "nlp", "data", "search", "gnn", "timeseries", "monitoring", "multimodal"]

[[bench]]
name = "neural_network_bench"
harness = false

[[bench]]
name = "ml_algorithms_bench"
harness = false

[lib]
name = "c19_ai"
path = "src/lib.rs"

[[example]]
name = "basic_ml"
path = "examples/basic_ml.rs"

[[example]]
name = "deep_learning"
path = "examples/deep_learning.rs"
required-features = ["candle", "burn", "dfdx"]

[[example]]
name = "nlp_pipeline"
path = "examples/nlp_pipeline.rs"
required-features = ["nlp"]

[[example]]
name = "computer_vision"
path = "examples/computer_vision.rs"
required-features = ["vision"]

[[example]]
name = "llm_chat"
path = "examples/llm_chat.rs"
required-features = ["llm"]

[[example]]
name = "vector_search"
path = "examples/vector_search.rs"
required-features = ["search", "data"]

[[example]]
name = "diffusion_model"
path = "examples/diffusion_model.rs"
required-features = ["candle"]

# [[example]]
# name = "reinforcement_learning"
# path = "examples/reinforcement_learning.rs"
# required-features = ["reinforcement"]  # 暂时禁用，存在pyo3安全漏洞

[[example]]
name = "graph_neural_network"
path = "examples/graph_neural_network.rs"
required-features = ["gnn"]

[[example]]
name = "time_series_forecasting"
path = "examples/time_series_forecasting.rs"
required-features = ["timeseries"]

[[example]]
name = "multimodal_ai"
path = "examples/multimodal_ai.rs"
required-features = ["multimodal"]

[[example]]
name = "federated_learning"
path = "examples/federated_learning.rs"
required-features = ["federated"]

[[example]]
name = "edge_ai"
path = "examples/edge_ai.rs"
required-features = ["edge"]

[[example]]
name = "quantum_ml"
path = "examples/quantum_ml.rs"
required-features = ["quantum"]