# Cargo Deny 配置文件 - 安全扫描和依赖管理

[advisories]
# 数据库URL
db-urls = [
    "https://github.com/RustSec/advisory-db",
]

[licenses]

[bans]

[sources]
# 允许的源
allow-registry = ["https://github.com/rust-lang/crates.io-index"]