[package]
name = "c04_generic"
version = "0.1.0"
edition = "2024"
resolver = "3"

[dependencies]
itertools = "0.12"
rayon = "1.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
thiserror = "1"


[lib]
name = "c04_generic"
path = "src/lib.rs"

[[bin]]
name = "c04_generic"
path = "src/bin/main.rs"
