[package]
name = "c04_generic"
version = "0.1.0"
edition = "2024"
resolver = "3"

[dependencies]
itertools = "0.12"
rayon = "1.10"
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }


[lib]
name = "c04_generic"
path = "src/lib.rs"

[[bin]]
name = "c04_generic"
path = "src/bin/main.rs"
