[package]
name = "c04_generic"
version = "0.1.0"
edition = "2024"
resolver = "3"
rust-version = "1.90"

[dependencies]
itertools = "0.14.0"
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
array-init = "2.1.0"
proc_macro_derive = { path = "proc_macro_derive" }
futures = "0.3.31"

[dev-dependencies]
criterion = { workspace = true }


[lib]
name = "c04_generic"
path = "src/lib.rs"

[[bin]]
name = "c04_generic"
path = "src/bin/main.rs"

[[bench]]
name = "micro_benchmarks"
harness = false
