[package]
name = "observability_demo"
version = "0.1.0"
edition = "2021"
authors = ["Rust Observability Demo"]
description = "完全独立的可观测性演示项目"

[workspace]

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[[bin]]
name = "observability_demo"
path = "main.rs"
