[package]
name = "{{project_name}}"
version = "0.1.0"
edition = "2024"
authors = ["{{author_name}}"]
description = "{{project_description}}"
license = "MIT"
repository = "{{repository_url}}"
documentation = "{{documentation_url}}"
homepage = "{{homepage_url}}"
keywords = ["{{keywords}}"]
categories = ["{{categories}}"]

[[bin]]
name = "{{project_name}}"
path = "src/main.rs"

[dependencies]
# Web framework
axum = { version = "0.7", features = ["macros", "tracing"] }
tokio = { version = "1.0", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Database
sqlx = { version = "0.7", features = [
    "runtime-tokio-rustls",
    "postgres",
    "chrono",
    "uuid",
] }

# Authentication
jsonwebtoken = "9.0"
argon2 = "0.5"

# Utilities
anyhow = "1.0"
thiserror = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
validator = { version = "0.16", features = ["derive"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Configuration
config = "0.14"
dotenvy = "0.15"

# HTTP client
reqwest = { version = "0.11", features = ["json"] }

# Development dependencies
[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.0"
criterion = "0.5"
proptest = "1.0"
mockall = "0.12"
rstest = "0.18"
testcontainers = "0.15"

# Features
[features]
default = ["std"]
std = []
dev = ["axum/debug"]

# Build configuration
[profile.dev]
debug = true
opt-level = 0
overflow-checks = true

[profile.release]
debug = false
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.test]
debug = true
opt-level = 0
overflow-checks = true

[profile.bench]
debug = false
opt-level = 3
lto = true
codegen-units = 1
