[package]
name = "c03_control_fn"
version = "0.1.0"
edition = "2024"
resolver = "3"

[dependencies]
tokio = { version = ">=1.44.1", features = ["full"] }

[lib]
name = "c03_control_fn"
path = "src/lib.rs"

[[bin]]
name = "c03_control_fn"
path = "src/bin/main.rs"