[databases]
default = "sqlite:///sqlite3.db"  # 默认数据库，可以根据需要更改

[databases.sqlite]
url = "sqlite:///sqlite3.db"
name = "sqlite"

[databases.mysql]
url = "mysql://root:d123456b@localhost:3306/test"
name = "mysql"

[databases.postgres]
url = "postgres://postgres:d123456b@localhost:5432/test"
name = "postgres"
