[package]
name = "{{project_name}}"
version = "0.1.0"
edition = "2024"
authors = ["{{author_name}}"]
description = "{{project_description}}"
license = "MIT"
repository = "{{repository_url}}"
documentation = "{{documentation_url}}"
homepage = "{{homepage_url}}"
keywords = ["{{keywords}}"]
categories = ["{{categories}}"]

[dependencies]
# Standard library dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"

# Development dependencies
[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.0"
criterion = "0.5"
proptest = "1.0"
mockall = "0.12"
rstest = "0.18"

# Documentation dependencies
[features]
default = ["std"]
std = []
doc = ["documentation"]

[dependencies.documentation]
optional = true
version = "1.0"

# Build configuration
[profile.dev]
debug = true
opt-level = 0
overflow-checks = true

[profile.release]
debug = false
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.test]
debug = true
opt-level = 0
overflow-checks = true

[profile.bench]
debug = false
opt-level = 3
lto = true
codegen-units = 1

# Metadata
[package.metadata.docs.rs]
features = ["doc"]
targets = ["x86_64-unknown-linux-gnu"]
rustc-args = ["--cfg", "docsrs"]
