[package]
name = "c17_iot"
edition = "2024"
resolver = "3"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
rdkafka = { version = "0.38.0", optional = true, features = ["tokio", "cmake-build"] }
influxdb2 = { version = "0.4", optional = true }
openssl = { version = "0.10", optional = true, features = ["vendored"] }

[dev-dependencies]
rumqttc = "0.25.0"
coap-lite = "0.13"
opentelemetry = "0.30"
opentelemetry_sdk = { version = "0.30", features = ["rt-tokio"] }
opentelemetry-stdout = "0.30"
opentelemetry-otlp = { version = "0.30", features = ["http-json", "grpc-tonic"] }
tonic = { workspace = true }
anyhow = { workspace = true }
sha2 = "0.10"
hex = "0.4"
hyper = { workspace = true, features = ["full"] }
hyper-util = { workspace = true }
http = { workspace = true }
prometheus = "0.14"
rustls = { workspace = true }
rustls-pemfile = { workspace = true }

[features]
default = []
kafka = ["dep:rdkafka"]
influx = ["dep:influxdb2"]
openssl-examples = ["dep:openssl"]

[[example]]
name = "kafka_producer"
path = "examples/kafka_producer.rs"
required-features = ["kafka"]

[[example]]
name = "influx_write"
path = "examples/influx_write.rs"
required-features = ["influx"]

[[example]]
name = "coap_dtls_openssl"
path = "examples/coap_dtls_openssl.rs"
required-features = ["openssl-examples"]