[package]
name = "ai-ml-frameworks"
version = "0.1.0"
edition = "2021"
authors = ["Rust Learning Project"]
description = "AI/ML框架集成与性能优化"

[dependencies]
# AI/ML框架
candle-core = "0.9.1"
candle-nn = "0.9.1"
candle-transformers = "0.9.1"
# tch = "0.17.0"  # 暂时注释，需要PyTorch库
# ort = "2.0.0"  # 暂时注释，版本可能有问题

# 异步运行时
tokio = { version = "1.47.1", features = ["full"] }

# 数据处理
ndarray = "0.16.0"
polars = { version = "0.51.0", features = ["lazy", "temporal", "strings"] }

# 序列化
serde = { version = "1.0.227", features = ["derive"] }
serde_json = "1.0.145"
bincode = "1.3.3"

# 错误处理
anyhow = "1.0.100"
thiserror = "2.0.16"

# 日志和追踪
tracing = "0.1.41"
tracing-subscriber = "0.3.20"

# 基准测试
criterion = "0.7.0"

# 性能监控
metrics = "0.24.2"
metrics-exporter-prometheus = "0.17.2"

# 数学计算
nalgebra = "0.33.0"
approx = "0.5.1"

# 图计算
petgraph = "0.8.2"

# 配置管理
config = "0.15.17"

[[bench]]
name = "ml_frameworks"
harness = false
