# Rust形式化验证框架增强自动化配置

# 验证配置
verification:
  # 启用的验证类型
  enabled_types:
    - type_safety
    - memory_safety
    - concurrency_safety
    - performance
    - security
  
  # 验证级别
  levels:
    - basic
    - intermediate
    - advanced
    - expert
  
  # 验证工具配置
  tools:
    clippy: true
    miri: true
    cargo_audit: true
    cargo_tarpaulin: true
    cargo_bench: true
    cargo_test: true
  
  # 验证参数
  parameters:
    clippy:
      strict_mode: true
      deny_warnings: true
      additional_lints:
        - clippy::all
        - clippy::pedantic
        - clippy::nursery
    
    miri:
      timeout: 600
      check_undefined_behavior: true
      check_data_races: true
    
    cargo_audit:
      timeout: 300
      check_vulnerabilities: true
      check_advisories: true
    
    cargo_tarpaulin:
      timeout: 600
      coverage_threshold: 80
      generate_html: true
      generate_xml: true

# 分析配置
analysis:
  # 复杂度阈值
  complexity_threshold: 10
  
  # 覆盖率阈值
  coverage_threshold: 80
  
  # 质量阈值
  quality_threshold: 85
  
  # 性能阈值
  performance_threshold: 70
  
  # 安全阈值
  security_threshold: 90
  
  # 分析工具
  tools:
    cyclomatic_complexity: true
    cognitive_complexity: true
    maintainability_index: true
    technical_debt: true

# 报告配置
reporting:
  # 生成报告类型
  generate_html: true
  generate_json: true
  generate_pdf: false
  generate_markdown: true
  
  # 邮件通知
  email_notification: false
  email_recipients: []
  
  # 报告保留
  report_retention_days: 30
  
  # 报告模板
  templates:
    html_template: "templates/report.html"
    markdown_template: "templates/report.md"
  
  # 报告内容
  content:
    include_details: true
    include_recommendations: true
    include_charts: true
    include_metrics: true

# 自动化配置
automation:
  # 自动修复
  auto_fix: false
  
  # 修复前备份
  backup_before_fix: true
  
  # 并行执行
  parallel_execution: true
  
  # 最大工作线程数
  max_workers: 4
  
  # 超时设置
  timeouts:
    verification: 600
    analysis: 300
    reporting: 120
  
  # 重试配置
  retry:
    max_attempts: 3
    backoff_factor: 2
    max_delay: 60

# 通知配置
notifications:
  # Slack通知
  slack:
    enabled: false
    webhook_url: ""
    channel: "#rust-verification"
  
  # Discord通知
  discord:
    enabled: false
    webhook_url: ""
    channel: "verification"
  
  # Teams通知
  teams:
    enabled: false
    webhook_url: ""
    channel: "verification"
  
  # 控制台输出
  console_output: true
  
  # 日志级别
  log_level: "INFO"

# 备份配置
backup:
  # 启用备份
  enabled: true
  
  # 修复前备份
  backup_before_fix: true
  
  # 备份保留天数
  backup_retention_days: 7
  
  # 备份位置
  backup_location: "./backups"
  
  # 备份格式
  backup_format: "tar.gz"
  
  # 压缩级别
  compression_level: 6

# 缓存配置
cache:
  # 启用缓存
  enabled: true
  
  # 缓存TTL（小时）
  cache_ttl_hours: 24
  
  # 缓存位置
  cache_location: "./cache"
  
  # 缓存大小限制（MB）
  max_cache_size_mb: 100
  
  # 缓存清理
  cleanup:
    enabled: true
    interval_hours: 6

# 性能配置
performance:
  # 最大并发检查数
  max_concurrent_checks: 5
  
  # 内存限制（MB）
  memory_limit_mb: 1024
  
  # CPU限制（核心数）
  cpu_limit_cores: 4
  
  # 磁盘限制（MB）
  disk_limit_mb: 5120
  
  # 网络超时（秒）
  network_timeout_seconds: 30

# 安全配置
security:
  # 启用安全检查
  enabled: true
  
  # 依赖安全检查
  dependency_security: true
  
  # 代码安全检查
  code_security: true
  
  # 配置安全检查
  config_security: true
  
  # 运行时安全检查
  runtime_security: true
  
  # 安全扫描工具
  scanners:
    - "cargo_audit"
    - "safety"
    - "cargo_geiger"

# 集成配置
integrations:
  # CI/CD集成
  ci_cd:
    github_actions: true
    gitlab_ci: true
    jenkins: true
    azure_devops: true
  
  # IDE集成
  ide:
    vscode: true
    intellij: true
    vim: true
    emacs: true
  
  # 版本控制集成
  vcs:
    git: true
    mercurial: false
    svn: false

# 监控配置
monitoring:
  # 启用监控
  enabled: true
  
  # 监控指标
  metrics:
    - "verification_time"
    - "success_rate"
    - "error_rate"
    - "performance_metrics"
  
  # 监控工具
  tools:
    prometheus: false
    grafana: false
    datadog: false
  
  # 告警配置
  alerts:
    enabled: false
    thresholds:
      success_rate: 90
      error_rate: 10
      verification_time: 300

# 实验性功能
experimental:
  # AI辅助验证
  ai_assistance: false
  
  # 机器学习预测
  ml_prediction: false
  
  # 自动代码生成
  auto_code_generation: false
  
  # 智能修复建议
  intelligent_fixes: false

# 调试配置
debug:
  # 启用调试模式
  enabled: false
  
  # 详细日志
  verbose_logging: false
  
  # 调试输出
  debug_output: false
  
  # 性能分析
  profiling: false
  
  # 内存分析
  memory_profiling: false
