# Rust形式化验证框架配置文件

# 框架基本信息
framework:
  version: "2.0"
  name: "Rust Formal Verification Framework"
  description: "Complete formal verification framework for Rust"
  maintainer: "Rust Formal Verification Team"
  license: "MIT"
  repository: "https://github.com/rust-lang/formal-verification"
  documentation: "https://docs.rust-lang.org/formal-verification"

# 验证设置
verification:
  enabled: true
  strict_mode: false
  check_types: true
  check_memory: true
  check_concurrency: true
  check_performance: true
  exclude_patterns:
    - "*.tmp"
    - "*.bak"
    - "target/**"
    - ".git/**"
    - "node_modules/**"

# 文档设置
documentation:
  enabled: true
  auto_generate: true
  include_examples: true
  include_proofs: true
  format:
    - "markdown"
    - "html"
    - "pdf"
  languages:
    - "zh-CN"
    - "en-US"

# 质量设置
quality:
  enabled: true
  coverage_threshold: 90
  accuracy_threshold: 95
  completeness_threshold: 85
  performance_threshold: 90
  quality_gates:
    - name: "基础质量门"
      threshold: 70
      description: "基础质量要求"
    - name: "良好质量门"
      threshold: 80
      description: "良好质量要求"
    - name: "优秀质量门"
      threshold: 90
      description: "优秀质量要求"
    - name: "卓越质量门"
      threshold: 95
      description: "卓越质量要求"

# 自动化设置
automation:
  enabled: true
  schedule: "daily"
  backup: true
  notification: true
  reporting: true
  auto_fix: false
  parallel_execution: true
  max_workers: 4

# 工具配置
tools:
  clippy:
    enabled: true
    strict: true
    additional_lints:
      - "clippy::all"
      - "clippy::pedantic"
      - "clippy::nursery"
    exclude_lints:
      - "clippy::too_many_arguments"
      - "clippy::needless_pass_by_value"
    timeout: 300

  miri:
    enabled: true
    check_undefined_behavior: true
    check_memory_leaks: true
    check_data_races: true
    check_stack_overflow: true
    timeout: 600
    memory_limit: "4GB"

  coq:
    enabled: true
    proof_check: true
    auto_prove: false
    timeout: 300
    max_proof_steps: 1000
    tactics:
      - "auto"
      - "intuition"
      - "omega"
      - "ring"
      - "lia"

  lean:
    enabled: true
    proof_check: true
    auto_prove: false
    timeout: 300
    max_proof_steps: 1000
    tactics:
      - "simp"
      - "rw"
      - "exact"
      - "apply"
      - "cases"

  rustdoc:
    enabled: true
    private: true
    theme: "ayu"
    include_tests: true
    generate_search_index: true

# 性能设置
performance:
  max_concurrent_checks: 4
  cache_results: true
  cache_ttl_hours: 24
  enable_progress_bar: true
  memory_limit: "8GB"
  cpu_limit: "80%"
  disk_limit: "10GB"

# 通知设置
notifications:
  slack_webhook: ""
  discord_webhook: ""
  teams_webhook: ""
  email_smtp: ""
  email_recipients: []
  enable_console_output: true
  log_level: "INFO"
  log_format: "json"

# 备份设置
backup:
  enabled: true
  backup_before_verification: true
  backup_retention_days: 7
  backup_location: "./backups"
  compression: true
  encryption: false

# 验证规则
validation_rules:
  type_safety:
    enabled: true
    strict_mode: false
    check_generics: true
    check_lifetimes: true
    check_traits: true
    check_impls: true

  memory_safety:
    enabled: true
    check_ownership: true
    check_borrowing: true
    check_lifetimes: true
    check_drop: true
    check_unsafe: true

  concurrency_safety:
    enabled: true
    check_data_races: true
    check_deadlocks: true
    check_atomic_operations: true
    check_send_sync: true
    check_async_safety: true

  performance:
    enabled: true
    check_time_complexity: true
    check_space_complexity: true
    check_allocations: true
    check_optimizations: true
    check_inlining: true

# 国际对标设置
international_benchmarking:
  enabled: true
  compare_with:
    - "MIT"
    - "Stanford"
    - "CMU"
    - "Berkeley"
    - "Harvard"
  benchmark_categories:
    - "theoretical_depth"
    - "practical_applicability"
    - "modernity"
    - "completeness"
    - "innovation"

# 教育推广设置
educational:
  enabled: true
  generate_examples: true
  generate_exercises: true
  generate_tutorials: true
  difficulty_levels:
    - "beginner"
    - "intermediate"
    - "advanced"
    - "expert"
  target_audiences:
    - "students"
    - "researchers"
    - "engineers"
    - "educators"

# 学术研究设置
academic:
  enabled: true
  paper_preparation: true
  conference_targets:
    - "POPL"
    - "PLDI"
    - "ICFP"
    - "OOPSLA"
    - "ESOP"
    - "TACAS"
  research_areas:
    - "type_theory"
    - "formal_verification"
    - "program_analysis"
    - "compiler_verification"
    - "concurrency_verification"

# 产业应用设置
industrial:
  enabled: true
  case_studies: true
  best_practices: true
  migration_guides: true
  performance_benchmarks: true
  target_industries:
    - "finance"
    - "healthcare"
    - "automotive"
    - "aerospace"
    - "blockchain"

# 社区建设设置
community:
  enabled: true
  contribution_guidelines: true
  code_of_conduct: true
  mentorship_program: true
  events_organization: true
  social_media:
    twitter: ""
    linkedin: ""
    youtube: ""

# 安全设置
security:
  enabled: true
  vulnerability_scanning: true
  dependency_checking: true
  secret_detection: true
  license_compliance: true
  security_audit: true

# 合规设置
compliance:
  enabled: true
  gdpr_compliance: true
  accessibility_compliance: true
  internationalization: true
  localization: true
  standards_compliance:
    - "ISO/IEC 25010"
    - "IEEE 830"
    - "RFC 2119"
