# Rust形式化验证框架配置文件

# 验证设置
verification:
  enabled: true
  strict_mode: false
  check_types: true
  check_memory: true
  check_concurrency: true
  check_performance: true
  exclude_patterns:
    - "*.tmp"
    - "*.bak"
    - "target/**"
    - ".git/**"

# 证明生成设置
proof_generation:
  enabled: true
  coq_enabled: true
  lean_enabled: true
  auto_generate: false
  proof_timeout: 300
  max_proof_depth: 100

# 质量评估设置
quality_assessment:
  enabled: true
  coverage_threshold: 80
  accuracy_threshold: 95
  performance_threshold: 90
  completeness_threshold: 85
  quality_gates:
    - name: "基础质量门"
      threshold: 70
    - name: "良好质量门"
      threshold: 80
    - name: "优秀质量门"
      threshold: 90

# 报告设置
reporting:
  generate_html: true
  generate_json: true
  generate_pdf: false
  email_notification: false
  email_recipients: []
  report_retention_days: 30
  include_detailed_logs: true

# 工具配置
tools:
  clippy:
    enabled: true
    strict_mode: true
    additional_lints:
      - "clippy::all"
      - "clippy::pedantic"
      - "clippy::nursery"
    exclude_lints:
      - "clippy::too_many_arguments"
      - "clippy::needless_pass_by_value"
    timeout: 300

  miri:
    enabled: true
    check_undefined_behavior: true
    check_memory_leaks: true
    check_data_races: true
    check_stack_overflow: true
    timeout: 600
    memory_limit: "4GB"

  coq:
    enabled: true
    proof_check: true
    auto_prove: false
    timeout: 300
    max_proof_steps: 1000
    tactics:
      - "auto"
      - "intuition"
      - "omega"
      - "ring"

  lean:
    enabled: true
    proof_check: true
    auto_prove: false
    timeout: 300
    max_proof_steps: 1000
    tactics:
      - "simp"
      - "rw"
      - "exact"
      - "apply"

# 性能设置
performance:
  max_concurrent_checks: 4
  cache_results: true
  cache_ttl_hours: 24
  enable_progress_bar: true
  memory_limit: "8GB"
  cpu_limit: "80%"

# 通知设置
notifications:
  slack_webhook: ""
  discord_webhook: ""
  teams_webhook: ""
  enable_console_output: true
  log_level: "INFO"

# 备份设置
backup:
  enabled: true
  backup_before_verification: true
  backup_retention_days: 7
  backup_location: "./backups"

# 验证规则
validation_rules:
  type_safety:
    enabled: true
    strict_mode: false
    check_generics: true
    check_lifetimes: true
    check_traits: true

  memory_safety:
    enabled: true
    check_ownership: true
    check_borrowing: true
    check_lifetimes: true
    check_drop: true

  concurrency_safety:
    enabled: true
    check_data_races: true
    check_deadlocks: true
    check_atomic_operations: true
    check_send_sync: true

  performance:
    enabled: true
    check_time_complexity: true
    check_space_complexity: true
    check_allocations: true
    check_optimizations: true

# 国际对标设置
international_benchmarking:
  enabled: true
  compare_with:
    - "MIT"
    - "Stanford"
    - "CMU"
    - "Berkeley"
  benchmark_categories:
    - "theoretical_depth"
    - "practical_applicability"
    - "modernity"
    - "completeness"

# 教育推广设置
educational:
  enabled: true
  generate_examples: true
  generate_exercises: true
  difficulty_levels:
    - "beginner"
    - "intermediate"
    - "advanced"
    - "expert"

# 学术研究设置
academic:
  enabled: true
  paper_preparation: true
  conference_targets:
    - "POPL"
    - "PLDI"
    - "ICFP"
    - "OOPSLA"
  research_areas:
    - "type_theory"
    - "formal_verification"
    - "program_analysis"
    - "compiler_verification"
