[package]
name = "c08_algorithms"
version = "0.1.0"
edition = "2024"
resolver = "3"

[dependencies]



[lib]
name = "c08_algorithms"
path = "src/lib.rs"

[[bin]]
name = "c08_algorithms"
path = "src/bin/main.rs"
