[package]
name = "c21_otlp"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
authors = ["Rust OTLP Team"]
description = "OpenTelemetry Protocol (OTLP) implementation with Rust 1.88+ features"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/c21_otlp"
keywords = ["opentelemetry", "otlp", "observability", "telemetry", "async", "grpc"]
categories = ["development-tools::debugging", "network-programming", "asynchronous"]

[dependencies]
# OpenTelemetry核心依赖 - 使用workspace版本
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-semantic-conventions = "0.30"

# OTLP导出器和传输
opentelemetry-otlp = { workspace = true }
opentelemetry-http = "0.30"

# 异步运行时和网络 - 使用workspace版本
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
futures = { workspace = true }

# gRPC和HTTP客户端 - 使用workspace版本
tonic = { workspace = true }
prost = { workspace = true }
hyper = { workspace = true }
hyper-tls = { workspace = true }
reqwest = { workspace = true, features = ["json"] }

# 序列化和反序列化 - 使用workspace版本
serde = { workspace = true }
serde_json = { workspace = true }
prost-types = { workspace = true }

# 并发和同步 - 使用workspace版本
parking_lot = { workspace = true }
crossbeam = { workspace = true }
dashmap = { workspace = true }

# 压缩算法 - 升级到最新版本
flate2 = "1.0"
brotli = "3.4"
zstd = "0.13"

# 异步trait - 使用workspace版本
async-trait = { workspace = true }

# 系统信息 - 使用workspace版本
num_cpus = { workspace = true }

# 随机数生成 - 使用workspace版本
rand = { workspace = true }

# 错误处理和日志 - 使用workspace版本
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

# 性能监控和指标 - 使用workspace版本
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }

# 配置管理 - 使用workspace版本
config = { workspace = true }
clap = { version = "4.0", features = ["derive"] }

# 2025年新增依赖 - 使用workspace版本
chrono = { workspace = true }
uuid = { workspace = true }
url = { workspace = true }
bytes = { workspace = true }

# 测试依赖 - 使用workspace版本
[dev-dependencies]
tokio-test = { workspace = true }
criterion = { workspace = true }
tempfile = { workspace = true }
proptest = { workspace = true }
mockall = { workspace = true }

# [[bench]]
# name = "otlp_benchmarks"
# harness = false
