[package]
name = "{{project_name}}"
version = "0.1.0"
edition = "2024"
authors = ["{{author_name}}"]
description = "{{project_description}}"
license = "MIT"
repository = "{{repository_url}}"
documentation = "{{documentation_url}}"
homepage = "{{homepage_url}}"
keywords = ["{{keywords}}"]
categories = ["{{categories}}"]

[[bin]]
name = "{{project_name}}"
path = "src/main.rs"

[dependencies]
# CLI framework
clap = { version = "4.0", features = ["derive", "env"] }

# Async runtime
tokio = { version = "1.0", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"

# Utilities
anyhow = "1.0"
thiserror = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
regex = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Configuration
config = "0.14"
dotenvy = "0.15"

# File operations
walkdir = "2.0"
glob = "0.3"

# HTTP client
reqwest = { version = "0.11", features = ["json"] }

# Progress bars
indicatif = "0.17"

# Colors
colored = "2.0"

# Development dependencies
[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.0"
criterion = "0.5"
proptest = "1.0"
mockall = "0.12"
rstest = "0.18"

# Features
[features]
default = ["std"]
std = []
dev = ["clap/color"]

# Build configuration
[profile.dev]
debug = true
opt-level = 0
overflow-checks = true

[profile.release]
debug = false
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.test]
debug = true
opt-level = 0
overflow-checks = true

[profile.bench]
debug = false
opt-level = 3
lto = true
codegen-units = 1
