[package]
name = "c10_networks"
version = "0.1.0"
edition = "2024"
resolver = "3"
build = "build.rs"

[dependencies]
# 异步运行时
tokio = { version = "1.0", features = ["full"] }
async-std = "1.12"

# 网络和字节处理
bytes = { version = "1.0", features = ["serde"] }
mio = "0.8"

# 抓包与报文解析（libpnet）
pnet = { version = "0.34", optional = true }
pnet_packet = { version = "0.34", optional = true }
pnet_datalink = { version = "0.34", optional = true }
pnet_transport = { version = "0.34", optional = true }

# 可选：离线 PCAP 支持
pcap = { version = "2", optional = true }

# 协议解析
nom = "7.0"
httparse = "1.8"
url = "2.4"

# 序列化和反序列化
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# 错误处理
thiserror = "1.0"
anyhow = "1.0"

# 日志和追踪
tracing = "0.1"
tracing-subscriber = "0.3"

# 加密和安全
ring = "0.17"
rustls = { version = "0.23", default-features = false, features = ["ring"], optional = true }
tokio-rustls = { version = "0.26", optional = true }
rustls-pemfile = { version = "2", optional = true }

# 测试和基准测试
criterion = { version = "0.5", features = ["html_reports"] }
futures = "0.3"
futures-util = "0.3"

# DNS 解析（Hickory-DNS，原 trust-dns）
hickory-resolver = { version = "0.24", features = ["tokio-runtime", "system-config", "dns-over-https-rustls", "dns-over-tls"] }
hickory-proto = "0.24"

# P2P 与 QUIC（新增）
libp2p = { version = "0.52", features = ["tokio", "tcp", "dns", "tls", "gossipsub", "kad", "noise", "yamux", "ping", "identify", "macros"] }
quinn = "0.11"
rcgen = "0.12"
# ACME（证书自动签发/续期）
instant-acme = "0.7"
# WebSocket
tokio-tungstenite = { version = "0.21", features = ["rustls-tls-webpki-roots"] }
tungstenite = "0.21"

# Protobuf / gRPC（对齐 tonic 0.11 → prost 0.12）
prost = "0.12"
tonic = { version = "0.11", features = ["transport"] }

[build-dependencies]
prost-build = "0.12"
tonic-build = "0.11"
protoc-bin-vendored = "3"

[dev-dependencies]
tokio-test = "0.4"

[[example]]
name = "tcp_echo_server"
path = "examples/tcp_echo_server.rs"

[[example]]
name = "tcp_client"
path = "examples/tcp_client.rs"

[[example]]
name = "http_client"
path = "examples/http_client.rs"

[[example]]
name = "websocket_demo"
path = "examples/websocket_demo.rs"

[[example]]
name = "p2p_minimal"
path = "examples/p2p_minimal.rs"

[[example]]
name = "ws_echo_server"
path = "examples/ws_echo_server.rs"

[[example]]
name = "ws_echo_client"
path = "examples/ws_echo_client.rs"

[[example]]
name = "udp_echo"
path = "examples/udp_echo.rs"

[[example]]
name = "arp_sniff"
path = "examples/arp_sniff.rs"

[[example]]
name = "tcp_monitor"
path = "examples/tcp_monitor.rs"

[[example]]
name = "udp_custom_demo"
path = "examples/udp_custom_demo.rs"

[[example]]
name = "pcap_offline"
path = "examples/pcap_offline.rs"

[[example]]
name = "pcap_live_tcp"
path = "examples/pcap_live_tcp.rs"

[[example]]
name = "dns_lookup"
path = "examples/dns_lookup.rs"

[[example]]
name = "unified_dns"
path = "examples/unified_dns.rs"

[[example]]
name = "dns_doh_dot"
path = "examples/dns_doh_dot.rs"

[[example]]
name = "dns_custom_ns"
path = "examples/dns_custom_ns.rs"

[[example]]
name = "dns_records"
path = "examples/dns_records.rs"

[[example]]
name = "dns_ptr"
path = "examples/dns_ptr.rs"

[[example]]
name = "dns_negative_cache"
path = "examples/dns_negative_cache.rs"

[[example]]
name = "grpc_server"
path = "examples/grpc_server.rs"

[[example]]
name = "grpc_client"
path = "examples/grpc_client.rs"

[[bench]]
name = "network_performance"
harness = false


[lib]
name = "c10_networks"
path = "src/lib.rs"

[features]
default = ["base"]
base = []
sniff = ["pnet", "pnet_packet", "pnet_datalink", "pnet_transport"]
offline = ["pcap", "pnet_packet"]
pcap_live = ["pcap", "pnet_packet"]
tls = ["rustls", "tokio-rustls", "rustls-pemfile"]

[[bin]]
name = "c10_networks"
path = "src/bin/main.rs"
