[package]
name = "c10_networks"
version = "0.1.0"
edition = "2024"
resolver = "3"
build = "build.rs"
rust-version = "1.89"

[dependencies]
# 异步运行时 - 使用工作区统一版本
tokio = { workspace = true }
async-std = { workspace = true }

# 网络和字节处理 - 使用工作区统一版本
bytes = { workspace = true, features = ["serde"] }
mio = { workspace = true }

# 抓包与报文解析（libpnet）- 更新到最新版本
pnet = { version = "0.35", optional = true }
pnet_packet = { version = "0.35", optional = true }
pnet_datalink = { version = "0.35", optional = true }
pnet_transport = { version = "0.35", optional = true }

# 可选：离线 PCAP 支持
pcap = { version = "2", optional = true }

# 协议解析 - 更新到最新版本
nom = "8.0"
httparse = "1.8"
url = { workspace = true }

# 序列化和反序列化 - 使用工作区统一版本
serde = { workspace = true }
serde_json = { workspace = true }

# 错误处理 - 使用工作区统一版本
thiserror = { workspace = true }
anyhow = { workspace = true }

# 日志和追踪 - 使用工作区统一版本
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# 加密和安全 - 使用工作区统一版本
ring = { workspace = true }
rustls = { workspace = true, optional = true }
tokio-rustls = { workspace = true, optional = true }
rustls-pemfile = { workspace = true, optional = true }

# 测试和基准测试 - 使用工作区统一版本
criterion = { workspace = true, features = ["html_reports"] }
futures = { workspace = true }
futures-util = { workspace = true }

# DNS 解析（Hickory-DNS，原 trust-dns）- 更新到最新版本
hickory-resolver = { version = "0.24", features = ["tokio-runtime", "system-config", "dns-over-https-rustls", "dns-over-tls"] }
hickory-proto = "0.24"

# P2P 与 QUIC（新增）- 更新到最新版本
libp2p = { version = "0.56", features = ["tokio", "tcp", "dns", "tls", "gossipsub", "kad", "noise", "yamux", "ping", "identify", "macros"] }
quinn = "0.11"
rcgen = { workspace = true }
# ACME（证书自动签发/续期）- 更新到最新版本
instant-acme = "0.8"
# WebSocket - 使用工作区统一版本
tokio-tungstenite = { workspace = true, features = ["rustls-tls-webpki-roots"] }
tungstenite = { workspace = true }

# Protobuf / gRPC（使用工作区统一版本）
prost = { workspace = true }
tonic = { workspace = true, features = ["transport"] }
tonic-prost = "0.14.2"

[build-dependencies]
prost-build = { workspace = true }
tonic-prost-build = "0.14.2"
protoc-bin-vendored = "3"

[dev-dependencies]
tokio-test = { workspace = true }
axum = { workspace = true }

[[example]]
name = "tcp_echo_server"
path = "examples/tcp_echo_server.rs"

[[example]]
name = "tcp_client"
path = "examples/tcp_client.rs"

[[example]]
name = "http_client"
path = "examples/http_client.rs"

[[example]]
name = "websocket_demo"
path = "examples/websocket_demo.rs"

[[example]]
name = "p2p_minimal"
path = "examples/p2p_minimal.rs"

[[example]]
name = "ws_echo_server"
path = "examples/ws_echo_server.rs"

[[example]]
name = "ws_echo_client"
path = "examples/ws_echo_client.rs"

[[example]]
name = "udp_echo"
path = "examples/udp_echo.rs"

[[example]]
name = "arp_sniff"
path = "examples/arp_sniff.rs"

[[example]]
name = "tcp_monitor"
path = "examples/tcp_monitor.rs"

[[example]]
name = "udp_custom_demo"
path = "examples/udp_custom_demo.rs"

[[example]]
name = "pcap_offline"
path = "examples/pcap_offline.rs"
required-features = ["offline"]

[[example]]
name = "pcap_live_tcp"
path = "examples/pcap_live_tcp.rs"
required-features = ["pcap_live"]

[[example]]
name = "dns_lookup"
path = "examples/dns_lookup.rs"

[[example]]
name = "unified_dns"
path = "examples/unified_dns.rs"

[[example]]
name = "dns_doh_dot"
path = "examples/dns_doh_dot.rs"

[[example]]
name = "dns_custom_ns"
path = "examples/dns_custom_ns.rs"

[[example]]
name = "dns_records"
path = "examples/dns_records.rs"

[[example]]
name = "dns_ptr"
path = "examples/dns_ptr.rs"

[[example]]
name = "dns_negative_cache"
path = "examples/dns_negative_cache.rs"

[[example]]
name = "grpc_server"
path = "examples/grpc_server.rs"

[[example]]
name = "grpc_client"
path = "examples/grpc_client.rs"

[[bench]]
name = "network_performance"
harness = false


[lib]
name = "c10_networks"
path = "src/lib.rs"

[features]
default = ["base"]
base = []
sniff = ["pnet", "pnet_packet", "pnet_datalink", "pnet_transport"]
offline = ["pcap", "pnet_packet"]
pcap_live = ["pcap", "pnet_packet"]
tls = ["rustls", "tokio-rustls", "rustls-pemfile"]

[[bin]]
name = "c10_networks"
path = "src/bin/main.rs"
