[package]
name = "proc_macro_derive"
version = "0.1.0"
edition = "2024"
resolver = "3"
rust-version = "1.90"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
