[package]
name = "c13_microservice_standalone"
version = "0.1.0"
edition = "2021"
authors = ["Rust Microservice Team"]
description = "现代Rust微服务框架集合 - 独立版本"
license = "MIT"

[dependencies]
# 异步运行时
tokio = { version = "1.44", features = ["full"] }
futures = "0.3"

# Web框架
axum = { version = "0.7", features = ["macros", "multipart", "tracing"] }

# 序列化
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# 日志和追踪
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
log = "0.4"
slog = "2.7"

# 数据库 - 简化版本
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "mysql", "chrono", "uuid"] }
diesel = { version = "2.1", features = ["postgres", "mysql", "chrono", "uuid"] }

# 消息队列
redis = { version = "0.25", features = ["tokio-comp", "connection-manager"] }

# 认证和授权
jsonwebtoken = "9.3"
uuid = { version = "1.10", features = ["v4", "serde"] }

# 时间处理
chrono = { version = "0.4", features = ["serde"] }

# 错误处理
anyhow = "1.0"
thiserror = "1.0"

# 其他工具
clap = { version = "4.5", features = ["derive"] }

[lib]
name = "c13_microservice_standalone"
path = "src/lib_simple.rs"

[[example]]
name = "opentelemetry_demo"
path = "examples/opentelemetry_demo.rs"

[[example]]
name = "orm_demo"
path = "examples/orm_demo.rs"

[[example]]
name = "messaging_demo"
path = "examples/messaging_demo.rs"

[[example]]
name = "discovery_demo"
path = "examples/discovery_demo.rs"