[package]
name = "intelligent-operations"
version = "0.1.0"
edition = "2024"
resolver = "3"
rust-version = "1.90"
authors = ["Rust AI Project"]
description = "智能运维和AI驱动的系统优化"

[dependencies]
# 异步运行时
tokio = { version = "1.47.1", features = ["full"] }

# 序列化
serde = { version = "1.0.227", features = ["derive"] }
serde_json = "1.0.145"

# 错误处理
anyhow = "1.0.100"
thiserror = "2.0.16"

# 日志和指标
tracing = "0.1.41"
metrics = "0.24.2"

# AI/ML 库
candle-core = "0.9.1"
candle-nn = "0.9.1"
candle-transformers = "0.9.1"
ndarray = "0.16.1"
nalgebra = "0.33.2"

# 数据处理
polars = "0.51.0"

# 网络和HTTP
reqwest = { version = "0.12.5", features = ["json", "rustls-tls"] }
hyper = { version = "1.3.1", features = ["full"] }

# 工具库
uuid = { version = "1.10.0", features = ["v4", "serde"] }
chrono = { version = "0.4.38", features = ["serde"] }
url = "2.5.7"
rand = "0.8.5"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "ai_benchmarks"
harness = false
