# Dependabot 配置
# Dependabot Configuration

version: 2
updates:
  # Rust 依赖更新
  # Rust dependencies updates
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 10
    reviewers:
      - "rust-webassembly-team"
    assignees:
      - "rust-webassembly-team"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
    ignore:
      # 忽略主要版本更新
      # Ignore major version updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      # WebAssembly 相关依赖
      # WebAssembly related dependencies
      webassembly:
        patterns:
          - "wasm-*"
          - "wasmtime"
          - "wasm-bindgen*"
          - "js-sys"
          - "web-sys"
        update-types:
          - "minor"
          - "patch"
      # 测试相关依赖
      # Testing related dependencies
      testing:
        patterns:
          - "criterion"
          - "proptest"
          - "tempfile"
        update-types:
          - "minor"
          - "patch"
      # 序列化相关依赖
      # Serialization related dependencies
      serialization:
        patterns:
          - "serde*"
          - "serde_json"
          - "serde_bytes"
        update-types:
          - "minor"
          - "patch"
      # 异步运行时依赖
      # Async runtime dependencies
      async:
        patterns:
          - "tokio*"
        update-types:
          - "minor"
          - "patch"
      # 数学和算法依赖
      # Math and algorithm dependencies
      math:
        patterns:
          - "num-*"
        update-types:
          - "minor"
          - "patch"
      # 工具库依赖
      # Utility library dependencies
      utilities:
        patterns:
          - "uuid"
          - "chrono"
          - "log"
          - "env_logger"
          - "thiserror"
          - "anyhow"
          - "bumpalo"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions 更新
  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    reviewers:
      - "rust-webassembly-team"
    assignees:
      - "rust-webassembly-team"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      # 核心 Actions
      # Core Actions
      core-actions:
        patterns:
          - "actions/checkout"
          - "actions/upload-artifact"
          - "actions/download-artifact"
          - "actions/cache"
        update-types:
          - "minor"
          - "patch"
      # Rust 工具链 Actions
      # Rust toolchain Actions
      rust-actions:
        patterns:
          - "dtolnay/rust-toolchain"
        update-types:
          - "minor"
          - "patch"
      # 发布相关 Actions
      # Release related Actions
      release-actions:
        patterns:
          - "actions/create-release"
          - "actions/upload-release-asset"
          - "peaceiris/actions-gh-pages"
        update-types:
          - "minor"
          - "patch"
      # 安全相关 Actions
      # Security related Actions
      security-actions:
        patterns:
          - "actions/setup-node"
        update-types:
          - "minor"
          - "patch"

  # Docker 依赖更新（如果有的话）
  # Docker dependencies updates (if any)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 3
    reviewers:
      - "rust-webassembly-team"
    assignees:
      - "rust-webassembly-team"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # npm 依赖更新（如果有的话）
  # npm dependencies updates (if any)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    reviewers:
      - "rust-webassembly-team"
    assignees:
      - "rust-webassembly-team"
    commit-message:
      prefix: "npm"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    groups:
      # 开发依赖
      # Development dependencies
      dev-dependencies:
        patterns:
          - "jest*"
          - "@wasm-tool/*"
        update-types:
          - "minor"
          - "patch"
