name: c17_iot CI

on:
  push:
    paths:
      - 'crates/c17_iot/**'
      - '.github/workflows/c17_iot_ci.yml'
  pull_request:
    paths:
      - 'crates/c17_iot/**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: fmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy -p c17_iot -- -D warnings

      - name: build
        run: cargo build -p c17_iot --all-features

      - name: test
        run: cargo test -p c17_iot --all-features


