name: Build mdBook docs

on:
  push:
    branches: [ main, master ]
    paths:
      - 'crates/c18_model/docs/**'
      - '.github/workflows/mdbook.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'crates/c18_model/docs/**'
      - '.github/workflows/mdbook.yml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo bin
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-mdbook-0

      - name: Install mdBook
        run: |
          if ! command -v mdbook >/dev/null 2>&1; then
            cargo install mdbook --locked
          fi

      - name: Build book
        working-directory: crates/c18_model/docs
        run: mdbook build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: c18-model-book
          path: crates/c18_model/docs/book

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: crates/c18_model/docs/book

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
