name: Weekly Navigation Consistency Report

on:
  schedule:
    - cron: '0 2 * * 1'  # 每周一 02:00 UTC 运行
  workflow_dispatch: {}

jobs:
  weekly-report:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Navigation Check
        id: navigation
        shell: pwsh
        run: |
          $report = "navigation_report_$(Get-Date -Format yyyyMMdd_HHmmss).txt"
          $result = .\scripts\navigation_injector.ps1 -Root . -CheckOnly 2>&1
          $result | Out-File -FilePath $report -Encoding UTF8
          Write-Host "Saved report to $report"
          echo "report_file=$report" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: weekly-navigation-report
          path: ${{ steps.navigation.outputs.report_file }}
