name: Performance Benchmarks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 4 * * *'  # 每天凌晨4点运行

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUST_LOG: debug

jobs:
  # 基准测试
  benchmark:
    name: Performance Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Run benchmarks
        run: cargo bench --all

  # 性能分析
  performance-analysis:
    name: Performance Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install performance tools
        run: |
          sudo apt-get update
          sudo apt-get install -y perf
          sudo apt-get install -y valgrind
          
      - name: Run performance analysis
        run: cargo profile-cpu

  # 内存分析
  memory-analysis:
    name: Memory Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install memory tools
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind
          sudo apt-get install -y massif-visualizer
          
      - name: Run memory analysis
        run: cargo profile-mem

  # CPU分析
  cpu-analysis:
    name: CPU Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install CPU tools
        run: |
          sudo apt-get update
          sudo apt-get install -y perf
          sudo apt-get install -y flamegraph
          
      - name: Run CPU analysis
        run: cargo profile-cpu

  # 并发性能测试
  concurrency-performance:
    name: Concurrency Performance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Run concurrency performance tests
        run: cargo bench --features concurrency

  # 异步性能测试
  async-performance:
    name: Async Performance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Run async performance tests
        run: cargo bench --features async

  # 内存性能测试
  memory-performance:
    name: Memory Performance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Run memory performance tests
        run: cargo bench --features memory

  # 网络性能测试
  network-performance:
    name: Network Performance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Run network performance tests
        run: cargo bench --features network

  # 数据库性能测试
  database-performance:
    name: Database Performance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Run database performance tests
        run: cargo bench --features database

  # 算法性能测试
  algorithm-performance:
    name: Algorithm Performance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Run algorithm performance tests
        run: cargo bench --features algorithm

  # 数据结构性能测试
  data-structure-performance:
    name: Data Structure Performance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Run data structure performance tests
        run: cargo bench --features data-structure

  # 性能回归测试
  performance-regression:
    name: Performance Regression
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Run performance regression tests
        run: cargo bench --features regression

  # 性能基准测试
  performance-baseline:
    name: Performance Baseline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Run performance baseline tests
        run: cargo bench --features baseline

  # 性能监控
  performance-monitoring:
    name: Performance Monitoring
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Run performance monitoring
        run: cargo bench --features monitoring

  # 性能报告
  performance-report:
    name: Performance Report
    runs-on: ubuntu-latest
    needs: [benchmark, performance-analysis, memory-analysis, cpu-analysis, concurrency-performance, async-performance, memory-performance, network-performance, database-performance, algorithm-performance, data-structure-performance, performance-regression, performance-baseline, performance-monitoring]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Generate performance report
        run: cargo bench --all -- --save-baseline main