[package]
name = "c18_model"
version = "0.2.0"
edition = "2024"
resolver = "3"

authors = ["c18_model Contributors <contributors@c18model.dev>"]
description = "Rust implementation of theoretical models for system modeling, machine learning, and formal methods"
license = "MIT OR Apache-2.0"
repository = "https://github.com/c18model/c18_model"
documentation = "https://docs.rs/c18_model"
homepage = "https://c18model.dev"
keywords = ["rust", "modeling", "machine-learning", "formal-methods", "mathematics", "queueing-theory", "statistics"]
categories = ["science", "algorithms", "mathematics", "simulation"]
readme = "README.md"
rust-version = "1.89"

[dependencies]
# 序列化和反序列化
serde = { workspace = true }
serde_json = { workspace = true }

# 错误处理
thiserror = { workspace = true }

# 已裁剪：异步运行时

# UUID生成
uuid = { workspace = true }

# 时间处理
chrono = { workspace = true }

# 随机数生成
fastrand = "2.0.0"

# 图算法
petgraph = { workspace = true }

# 已裁剪：并行计算

# 数值计算
num-traits = "0.2.0"
num-derive = "0.3.0"

# 统计计算
statrs = "0.18.0"

# 数学函数
libm = "0.2.0"

# 运行时/示例适配基础依赖（对齐到 workspace 或最新主线）
tokio = { workspace = true, features = ["rt-multi-thread", "sync", "time"], optional = true }
tokio-util = { workspace = true, features = ["rt"], optional = true }
async-std = { version = "1.0.0", features = ["attributes"], optional = true }
async-channel = { version = "2.0.0", optional = true }
tower = { workspace = true, features = ["limit", "timeout", "retry", "util"], optional = true }
http = { workspace = true, optional = true }
hyper = { workspace = true, features = ["client", "http1"], optional = true }

[dev-dependencies]
# 基准测试
criterion = { workspace = true, features = ["html_reports"] }

# 属性测试
proptest = { workspace = true }

# 测试工具
tempfile = { workspace = true }

# 文档测试
doc-comment = "0.3.0"

# 并发模型验证
loom = "0.7.0"

[features]
default = ["std"]
std = []
no-std = []
## 已裁剪：async/visualization/benchmarks/parallel 等特性

# 运行时/示例适配（通过 features 选择，依赖为可选）
tokio-adapter = ["dep:tokio", "dep:tokio-util"]
async-std-adapter = ["dep:async-std", "dep:async-channel"]
tower-examples = ["dep:tower", "dep:http", "dep:hyper"]
c20-integration = ["dep:c20_distributed"]

[dependencies.c20_distributed]
path = "../c20_distributed"
optional = true

# 已裁剪：nalgebra / plotly / wasm-bindgen 及 wasm 目标依赖

[[bench]]
name = "concurrency_bench"
harness = false

# Profile configurations are managed at workspace root level
