[package]
name = "c18_model"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = ">=1.44.1", features = ["full"] }
actix = ">=0.13"
serde = { version = ">=1.0.219", features = ["derive"] }
serde_json = ">=1.0.140"
